# This file was generated by team member Zhong Jun Khoo(20612661)
import json
import time
import os
from datetime import datetime

class LogSimulator:
    """
    Simulate running by replaying log files
    """
    
    def __init__(self, log_dir='logs/simulator_logs'):
        self.log_dir = log_dir
        self.log_files = []
        
    def list_log_files(self):
        """List all available log files"""
        if not os.path.exists(self.log_dir):
            print(f"Directory {self.log_dir} not found")
            return []
        
        files = [f for f in os.listdir(self.log_dir) if f.endswith('.json')]
        files.sort()
        return files
    
    def load_log_file(self, filename):
        """Load a specific log file"""
        filepath = os.path.join(self.log_dir, filename)
        entries = []

        with open(filepath, 'r', encoding='utf-8') as f:
            raw = f.read().strip()

        if not raw:
            return entries

        # Fast path: JSONL (one JSON object per line)
        for line in raw.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                if isinstance(entry, dict):
                    entries.append(entry)
            except json.JSONDecodeError:
                # Fall back to concatenated pretty-printed JSON objects.
                entries = []
                break

        if entries:
            return entries

        # Fallback: parse concatenated JSON objects, e.g. "{}\n{}\n{}"
        decoder = json.JSONDecoder()
        idx = 0
        n = len(raw)
        while idx < n:
            while idx < n and raw[idx].isspace():
                idx += 1
            if idx >= n:
                break
            try:
                entry, next_idx = decoder.raw_decode(raw, idx)
                if isinstance(entry, dict):
                    entries.append(entry)
                idx = next_idx
            except json.JSONDecodeError:
                # Skip one character and continue to avoid hard failure on bad fragments.
                idx += 1

        return entries
    
    def simulate(self, filename=None, speed=1.0):
        """
        Simulate running by replaying log entries
        
        Args:
            filename: Specific log file to replay (None for most recent)
            speed: Playback speed multiplier (1.0 = real-time)
        """
        # Get log files
        files = self.list_log_files()
        if not files:
            print("No log files found")
            return
        
        # Select file
        if filename:
            if filename not in files:
                print(f"File {filename} not found")
                return
            selected = filename
        else:
            selected = files[-1]  # Most recent
        
        print(f"Loading: {selected}")
        entries = self.load_log_file(selected)
        print(f"Loaded {len(entries)} entries")
        
        # Replay
        start_time = None
        for i, entry in enumerate(entries):
            data = entry['data']

            if i == 0:
                start_time = datetime.fromisoformat(entry['timestamp'])
                print(f"\n{'='*50}")
                print(f"Starting simulation from: {entry['timestamp']}")
                print(f"{'='*50}\n")
            
            # Calculate delay based on timestamps
            if i > 0:
                if "--- Round" in data and "Aggregation: Standard ---" in data:
                    time.sleep(1)
                elif "--- Round" in data and "Analysis ---" in data:
                    time.sleep(0.5)
                else:
                    current_time = datetime.fromisoformat(entry['timestamp'])
                    prev_time = datetime.fromisoformat(entries[i-1]['timestamp'])
                    delay = (current_time - prev_time).total_seconds() / speed
                    if delay > 0:
                        time.sleep(delay)
            
            # Print the data
            print(f"{data}", flush= True)

    
    
# Command line usage
if __name__ == "__main__":

    import argparse
    
    parser = argparse.ArgumentParser(description='Simulate training from logs')
    parser.add_argument('--file', help='Specific log file to replay')
    parser.add_argument('--speed', type=float, default=1.0, help='Playback speed')
    parser.add_argument('--list', action='store_true', help='List available log files')
    
    args = parser.parse_args()
    
    simulator = LogSimulator()
    
    
    if args.list:
        files = simulator.list_log_files()
        print("\nAvailable log files:")
        for i, f in enumerate(files, 1):
            print(f"{i}. {f}")
    
    else:
        simulator.simulate(args.file, args.speed)

        