"""
Main entry point for running all tests
"""
# This file was generated by team member Xinchen Dai(20616310)
import sys
import os
import unittest

# Add project root directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import all test modules
from tests.test_model_types import run_model_type_tests
from tests.test_flower_protocol import run_flower_protocol_tests
from tests.test_model_aggregation import run_model_aggregation_tests


def run_all_tests():
    """Run all tests"""
    print("\n" + "="*70)
    print("Federated Learning System Test Suite")
    print("="*70)
    
    results = {
        "model_type": run_model_type_tests(),
        "flower_protocol": run_flower_protocol_tests(),
        "model_aggregation": run_model_aggregation_tests()
    }
    
    print("\n" + "="*70)
    print("Test Results Summary")
    print("="*70)
    
    for test_name, passed in results.items():
        status = "PASSED" if passed else "FAILED"
        print(f"{test_name}: {status}")
    
    all_passed = all(results.values())
    print("\n" + "="*70)
    if all_passed:
        print("All tests passed!")
    else:
        print("Some tests failed. Please check the output above.")
    print("="*70)
    
    return all_passed


if __name__ == "__main__":
    run_all_tests()