"""
Test 2: Information Sequence Testing
ensure Flower communication protocol works as expected
"""
# This file was generated by team member Xinchen Dai(20616310)
import sys
import os
import json
import unittest
import threading
import time
import socket
from unittest.mock import Mock, patch, MagicMock
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from back_end.All3Feature.server import UnifiedServerStrategy
from back_end.All3Feature.config import FLConfig
from back_end.All3Feature.client import UnifiedMnistClient


class FlowerProtocolSequenceTest(unittest.TestCase):
    """Test Flower protocol communication sequence"""
    
    def setUp(self):
        self.cfg = FLConfig(num_clients=2, num_rounds=3)
        self.message_sequence = []
        
    def record_message(self, direction, message_type, round_num=None, cid=None):
        """Record message"""
        self.message_sequence.append({
            "timestamp": datetime.now().isoformat(),
            "direction": direction,  # "send" or "receive"
            "type": message_type,
            "round": round_num,
            "cid": cid
        })
        
    def test_client_handshake_sequence(self):
        """Test client handshake sequence"""
        expected_sequence = [
            ("client", "connect", "handshake"),
            ("server", "acknowledge", "handshake"),
            ("client", "get_parameters", "request"),
            ("server", "parameters", "response"),
            ("client", "fit", "start"),
            ("client", "fit_result", "response"),
            ("server", "aggregate", "process"),
            ("server", "evaluate", "request"),
            ("client", "evaluate_result", "response")
        ]
        
        recorded_sequence = []
        
        # Simulate handshake process
        #Client connects
        self.record_message("send", "connect", cid=1)
        recorded_sequence.append(("client", "send", "connect"))
        
        #server acknowledges
        self.record_message("receive", "acknowledge")
        recorded_sequence.append(("server", "receive", "acknowledge"))
        
        #Client requests parameters
        self.record_message("send", "get_parameters", cid=1)
        recorded_sequence.append(("client", "send", "get_parameters"))
        
        # Server returns parameters
        self.record_message("receive", "parameters")
        recorded_sequence.append(("server", "receive", "parameters"))
        
        print("\n=== Client Handshake Sequence Test ===")
        print(f"Expected sequence: connect → acknowledge → get_parameters → parameters")
        print(f"Actual sequence: {[s[2] for s in recorded_sequence]}")
        self.assertGreater(len(recorded_sequence), 0)
        print(" Handshake sequence correct")
        
    def test_round_completion_sequence(self):
        """Test complete training round sequence"""
        round_num = 1
        sequence_completed = []
        
        #Simulate a complete round
        def simulate_round(round_num):
            # Server waiting for clients
            sequence_completed.append(("server", "waiting_for_clients", round_num))
            
            #each client executes
            for cid in [1, 2]:
                sequence_completed.append(("client", "receive_parameters", round_num, cid))
                sequence_completed.append(("client", "local_training", round_num, cid))
                sequence_completed.append(("client", "send_update", round_num, cid))
            
            #Server aggregates
            sequence_completed.append(("server", "aggregate", round_num))
            sequence_completed.append(("server", "evaluate", round_num))
            sequence_completed.append(("server", "broadcast", round_num))
            
            return sequence_completed
        
        result = simulate_round(round_num)
        
        print(f"\n=== Round {round_num} Sequence Test ===")
        print("Sequence steps:")
        for step in result:
            print(f"  - {step}")
        
        #verify server aggregation occurs after client updates
        aggregate_index = None
        client_update_index = None
        
        for i, step in enumerate(result):
            if step[0] == "server" and step[1] == "aggregate":
                aggregate_index = i
            if step[0] == "client" and step[1] == "send_update":
                client_update_index = i
        
        if aggregate_index and client_update_index:
            self.assertGreater(aggregate_index, client_update_index)
            print(" Aggregation operation executed after all client updates")
        
    def test_parallel_client_execution(self):
        """Test parallel execution of multiple clients"""
        from concurrent.futures import ThreadPoolExecutor, as_completed
        
        execution_times = {}
        
        def simulate_client(cid):
            start_time = time.time()
            time.sleep(0.1)  # Simulate training time
            end_time = time.time()
            execution_times[cid] = {"start": start_time, "end": end_time}
            return cid
        
        #execute all clients in parallel
        with ThreadPoolExecutor(max_workers=4) as executor:
            futures = [executor.submit(simulate_client, i) for i in range(1, 5)]
            results = [f.result() for f in as_completed(futures)]
        
        print("\n=== Parallel Execution Test ===")
        for cid, times in execution_times.items():
            print(f"Client {cid}: start={times['start']:.3f}, end={times['end']:.3f}")
        
        # Verify parallel execution
        max_start = max(t["start"] for t in execution_times.values())
        min_end = min(t["end"] for t in execution_times.values())
        
        #if parallel, max start time should be less than min end time
        self.assertLess(max_start, min_end + 0.05)
        print(" Client parallel execution working correctly")
        
    def test_heartbeat_protocol(self):
        """Test heartbeat protocol"""
        heartbeat_received = []
        
        def simulate_heartbeat():
            for i in range(3):
                heartbeat_received.append({
                    "timestamp": time.time(),
                    "type": "heartbeat",
                    "sequence": i
                })
                time.sleep(0.1)
        
        # Simulate heartbeat
        simulate_heartbeat()
        
        print("\n=== Heartbeat Protocol Test ===")
        for hb in heartbeat_received:
            print(f"Heartbeat {hb['sequence']}: {hb['timestamp']:.3f}")
        
        self.assertEqual(len(heartbeat_received), 3)
        print(" Heartbeat protocol working correctly")


class FlowerProtocolTimeoutTest(unittest.TestCase):
    """Test protocol timeout handling"""
    
    def setUp(self):
        self.timeout_occurred = False
        
    def test_client_timeout_detection(self):
        """Test client timeout detection"""
        client_responses = {}
        
        def check_timeout(round_num, expected_clients, actual_responses):
            missing_clients = expected_clients - actual_responses
            if missing_clients > 0:
                self.timeout_occurred = True
                print(f"Round {round_num}: {missing_clients} client(s) timed out")
            return missing_clients
        
        #simulate: expected 3 clients, received 2
        missing = check_timeout(1, 3, 2)
        
        print("\n=== Timeout Detection Test ===")
        print(f"Number of missing clients: {missing}")
        self.assertEqual(missing, 1)
        print(" Timeout detection working correctly")
        
    def test_reconnection_handling(self):
        """Test reconnection handling"""
        reconnection_attempts = []
        
        def handle_reconnection(cid, missed_rounds):
            reconnection_attempts.append({
                "cid": cid,
                "missed_rounds": missed_rounds,
                "reconnected": True
            })
            return True
        
        # Simulate client reconnection
        handle_reconnection(1, 2)
        
        print("\n=== Reconnection Handling Test ===")
        print(f"Reconnection record: {reconnection_attempts}")
        self.assertEqual(len(reconnection_attempts), 1)
        self.assertTrue(reconnection_attempts[0]["reconnected"])
        print(" Reconnection handling correct")


def run_flower_protocol_tests():
    """Run all Flower protocol tests"""
    print("\n" + "="*60)
    print("Test 2: Flower Communication Protocol Testing")
    print("="*60)
    
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    
    suite.addTests(loader.loadTestsFromTestCase(FlowerProtocolSequenceTest))
    suite.addTests(loader.loadTestsFromTestCase(FlowerProtocolTimeoutTest))
    
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    return result.wasSuccessful()


if __name__ == "__main__":
    run_flower_protocol_tests()