"""
Test 3: Model Aggregation Testing
ensure the aggregated model is the average (or other reasonable aggregation result) of client input models
"""
# This file was generated by team member Xinchen Dai(20616310)
import sys
import os
import json
import unittest
import numpy as np
import torch
import torch.nn as nn

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from back_end.All3Feature.server import UnifiedServerStrategy
from back_end.All3Feature.config import FLConfig
from back_end.All3Feature.utils import Net, train, test
from back_end.All3Feature.features.robustness import aggregate_with_mad_reputation


class ModelAggregationTest(unittest.TestCase):
    """Test model aggregation functionality"""
    
    def setUp(self):
        self.cfg = FLConfig(
            num_clients=3,
            num_rounds=5,
            use_he=False,
            use_defense=False
        )
        self.strategy = UnifiedServerStrategy(self.cfg)
        
    def test_fedavg_aggregation(self):
        """Test standard FedAvg aggregation"""
        #create several different model parameters
        model1 = Net()
        model2 = Net()
        model3 = Net()
        
        # Set different parameters for each model
        for name, param in model1.named_parameters():
            param.data.fill_(1.0)
        
        for name, param in model2.named_parameters():
            param.data.fill_(2.0)
            
        for name, param in model3.named_parameters():
            param.data.fill_(3.0)
        
        #Extract parameters
        params1 = [val.detach().cpu().numpy() for _, val in model1.state_dict().items()]
        params2 = [val.detach().cpu().numpy() for _, val in model2.state_dict().items()]
        params3 = [val.detach().cpu().numpy() for _, val in model3.state_dict().items()]
        
        #simulate client weights (each client has the same number of samples)
        weights_results = [
            (1, params1, 100, {}),
            (2, params2, 100, {}),
            (3, params3, 100, {})
        ]
        
        #Manually calculate expected average
        num_layers = len(params1)
        expected_avg = []
        for layer_idx in range(num_layers):
            layer_avg = (params1[layer_idx] + params2[layer_idx] + params3[layer_idx]) / 3
            expected_avg.append(layer_avg)
        
        #Use FedAvg aggregation
        aggregated = self._manual_fedavg_aggregate(weights_results)
        
        print("\n=== FedAvg Aggregation Test ===")
        print(f"Model 1 parameter value: {params1[0][0,0]}")
        print(f"Model 2 parameter value: {params2[0][0,0]}")
        print(f"Model 3 parameter value: {params3[0][0,0]}")
        print(f"Expected average: {expected_avg[0][0,0]}")
        print(f"Actual aggregated value: {aggregated[0][0,0]}")
        
        #verify aggregation result
        for layer_idx in range(num_layers):
            np.testing.assert_array_almost_equal(
                aggregated[layer_idx], 
                expected_avg[layer_idx],
                decimal=5
            )
        
        print(" FedAvg aggregation result correct")
        
    def _manual_fedavg_aggregate(self, weights_results):
        """Manual implementation of FedAvg aggregation"""
        cids = [cid for cid, _, _, _ in weights_results]
        all_weights = [nds for _, nds, _, _ in weights_results]
        num_examples = [w for _, _, w, _ in weights_results]
        
        total_examples = sum(num_examples)
        weights_normalized = [w / total_examples for w in num_examples]
        
        num_layers = len(all_weights[0])
        aggregated = []
        
        for layer_idx in range(num_layers):
            layer_sum = None
            for client_idx, weights in enumerate(all_weights):
                layer_weight = weights[layer_idx] * weights_normalized[client_idx]
                if layer_sum is None:
                    layer_sum = layer_weight
                else:
                    layer_sum += layer_weight
            aggregated.append(layer_sum)
        
        return aggregated
    
    def test_weighted_aggregation(self):
        """Test weighted aggregation"""
        #Clients with different sample sizes
        params1 = [np.ones((5, 5))]
        params2 = [np.ones((5, 5)) * 2]
        params3 = [np.ones((5, 5)) * 3]
        
        weights_results = [
            (1, params1, 50, {}),   # 50 samples
            (2, params2, 100, {}),  # 100 samples
            (3, params3, 150, {})   # 150 samples
        ]
        
        total_samples = 50 + 100 + 150
        
        #Manually calculate weighted average
        expected = (params1[0] * 50 + params2[0] * 100 + params3[0] * 150) / total_samples
        
        #aggregate
        aggregated = self._manual_fedavg_aggregate(weights_results)
        
        print("\n=== Weighted Aggregation Test ===")
        print(f"Client 1: 50 samples, value=1")
        print(f"Client 2: 100 samples, value=2")
        print(f"Client 3: 150 samples, value=3")
        print(f"Expected weighted average: {expected[0,0]}")
        print(f"Actual aggregated value: {aggregated[0][0,0]}")
        
        np.testing.assert_array_almost_equal(aggregated[0], expected, decimal=5)
        print(" Weighted aggregation result correct")
    
    def test_empty_client_handling(self):
        """Test handling when no client updates"""
        weights_results = []
        
        print("\n=== Empty Client Handling Test ===")
        if not weights_results:
            print("No client updates, keeping original parameters")
        
        self.assertEqual(len(weights_results), 0)
        print(" Correct handling of empty client case")
    
    def test_single_client_aggregation(self):
        """Test single client aggregation"""
        params = [np.array([[1.0, 2.0], [3.0, 4.0]])]
        weights_results = [(1, params, 100, {})]
        
        aggregated = self._manual_fedavg_aggregate(weights_results)
        
        print("\n=== Single Client Aggregation Test ===")
        print(f"Original parameters: {params[0]}")
        print(f"Aggregated result: {aggregated[0]}")
        
        np.testing.assert_array_equal(aggregated[0], params[0])
        print(" Single client aggregation result correct")


class PrivacyPreservingAggregationTest(unittest.TestCase):
    """Test privacy-preserving aggregation (HE mode)"""
    
    def setUp(self):
        self.cfg = FLConfig(
            num_clients=3,
            use_he=True,
            he_encrypt_ratio=0.02
        )
        
    def test_he_aggregation_structure(self):
        """Test HE aggregation data structure"""
        print("\n=== HE Aggregation Structure Test ===")
        
        #verify HE-related configurations
        self.assertTrue(self.cfg.use_he)
        self.assertGreater(self.cfg.he_encrypt_ratio, 0)
        
        print(f"HE encryption ratio: {self.cfg.he_encrypt_ratio}")
        print(f"HE mask seed: {self.cfg.he_mask_seed}")
        print(" HE aggregation configuration correct")


class DefenseAggregationTest(unittest.TestCase):
    """Test defensive aggregation (MAD + Reputation)"""
    
    def setUp(self):
        self.cfg = FLConfig(
            num_clients=3,
            use_defense=True,
            defense_sigma=2.0,
            trust_ema_alpha=0.7
        )
        self.client_trusts = {1: 1.0, 2: 1.0, 3: 1.0}
        self.client_trust_history = {1: [], 2: [], 3: []}
        
    def test_mad_reputation_aggregation(self):
        """Test MAD+Reputation aggregation"""
        #create clients with different parameters
        params1 = [np.ones((3, 3))]      # Normal
        params2 = [np.ones((3, 3)) * 2]  # Normal
        params3 = [np.ones((3, 3)) * 10] # Anomaly
        
        weights_results = [
            (1, params1, 100, False),
            (2, params2, 100, False),
            (3, params3, 100, False)
        ]
        
        #use defensive aggregation
        aggregated = aggregate_with_mad_reputation(
            self.cfg,
            weights_results,
            self.client_trusts,
            self.client_trust_history
        )
        
        print("\n=== MAD+Reputation Aggregation Test ===")
        print(f"Client 1 parameter value: {params1[0][0,0]}")
        print(f"Client 2 parameter value: {params2[0][0,0]}")
        print(f"Client 3 parameter value: {params3[0][0,0]} (anomaly)")
        print(f"Defensive aggregation result: {aggregated[0][0,0]}")
        
        #Defensive aggregation should reduce the impact of anomalies
        #Result should be closer to normal average than full average
        normal_avg = (1 + 2) / 2
        full_avg = (1 + 2 + 10) / 3
        
        self.assertLess(abs(aggregated[0][0,0] - normal_avg), 
                        abs(aggregated[0][0,0] - full_avg))
        
        print(f"Normal average: {normal_avg}")
        print(f"Full average: {full_avg}")
        print(" Defensive aggregation effectively reduces impact of anomalies")
        
    def test_trust_update(self):
        """Test trust update"""
        #simulate trust update after one round of aggregation
        round_scores = {1: 0.95, 2: 0.93, 3: 0.45}
        alpha = self.cfg.trust_ema_alpha
        
        updated_trusts = {}
        for cid in [1, 2, 3]:
            old_trust = self.client_trusts.get(cid, 1.0)
            new_trust = alpha * old_trust + (1 - alpha) * round_scores[cid]
            updated_trusts[cid] = new_trust
        
        print("\n=== Trust Update Test ===")
        print(f"Client 3 trust: {self.client_trusts[3]:.4f} → {updated_trusts[3]:.4f}")
        self.assertLess(updated_trusts[3], self.client_trusts[3])
        print(" Anomalous client's trust is reduced")


def run_model_aggregation_tests():
    """Run all model aggregation tests"""
    print("\n" + "="*60)
    print("Test 3: Model Aggregation Testing")
    print("="*60)
    
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    
    suite.addTests(loader.loadTestsFromTestCase(ModelAggregationTest))
    suite.addTests(loader.loadTestsFromTestCase(PrivacyPreservingAggregationTest))
    suite.addTests(loader.loadTestsFromTestCase(DefenseAggregationTest))
    
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    return result.wasSuccessful()


if __name__ == "__main__":
    run_model_aggregation_tests()