"""
Test 1: Model Type Testing
verify that the system issues warnings when different nodes submit different model types
"""
# This file was generated by team member Xinchen Dai(20616310)
import sys
import os
import json
import unittest
from unittest.mock import Mock, patch, MagicMock
import numpy as np
import torch
import torch.nn as nn

#Add project root directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from back_end.All3Feature.server import UnifiedServerStrategy
from back_end.All3Feature.config import FLConfig
from back_end.All3Feature.utils import Net


class DifferentModelNet(nn.Module):
    """A model with different structure for testing model type detection"""
    
    def __init__(self):
        super().__init__()
        #Different layer structure: single convolution + different fully connected layers
        self.conv1 = nn.Conv2d(1, 8, 3)  #different output channels
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(8, 16, 3)
        self.fc1 = nn.Linear(16 * 5 * 5, 100)  #different input dimensions
        self.fc2 = nn.Linear(100, 10)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = torch.relu(self.fc1(x))
        return self.fc2(x)


class ModelTypeWarningTest(unittest.TestCase):
    """Test warning mechanism for model type mismatch"""
    
    def setUp(self):
        """Preparation before tests"""
        self.cfg = FLConfig(
            num_clients=3,
            num_rounds=5,
            server_address="127.0.0.1:8080",
            use_he=False,
            use_defense=False,
            use_random_disconnection=False
        )
        self.strategy = UnifiedServerStrategy(self.cfg)
        
    def test_model_structure_detection(self):
        """Test model structure detection functionality"""
        standard_model = Net()
        different_model = DifferentModelNet()
        
        #extract model structure information
        standard_structure = self._extract_model_structure(standard_model)
        different_structure = self._extract_model_structure(different_model)
        
        #verify structures are different
        self.assertNotEqual(standard_structure, different_structure)
        
        print("\n=== Model Structure Detection Test ===")
        print(f"Standard model structure: {standard_structure}")
        print(f"Different model structure: {different_structure}")
        print(" Model structure detection working correctly")
    
    def _extract_model_structure(self, model):
        """Extract model structure features for comparison"""
        structure = {
            "layer_names": [],
            "layer_shapes": []
        }
        
        for name, module in model.named_modules():
            if isinstance(module, (nn.Conv2d, nn.Linear)):
                structure["layer_names"].append(name)
                if isinstance(module, nn.Conv2d):
                    structure["layer_shapes"].append(f"Conv2d({module.in_channels},{module.out_channels})")
                else:
                    structure["layer_shapes"].append(f"Linear({module.in_features},{module.out_features})")
        
        return structure
    
    def test_server_parameter_comparison(self):
        """Test server-side parameter comparison functionality"""
        #Simulate parameters received from different clients
        
        #Client 1 Standard model parameters
        standard_model = Net()
        params_standard = [val.cpu().numpy() for _, val in standard_model.state_dict().items()]
        
        #Client 2 Different model parameters
        different_model = DifferentModelNet()
        params_different = [val.cpu().numpy() for _, val in different_model.state_dict().items()]
        
        # Verify different parameter counts
        self.assertNotEqual(len(params_standard), len(params_different))
        
        print("\n=== Parameter Length Comparison Test ===")
        print(f"Standard model parameter count: {len(params_standard)}")
        print(f"Different model parameter count: {len(params_different)}")
        print(" Server can detect parameter count differences")
    
    def test_warning_trigger_condition(self):
        """Test warning trigger conditions"""
        warnings_triggered = []
        
        # Simulate parameter validation function
        def validate_parameters(params_list):
            """Validate if parameters come from the same model structure"""
            if not params_list:
                return True
            
            first_shape = [p.shape for p in params_list[0]]
            
            for i, params in enumerate(params_list[1:], 2):
                current_shape = [p.shape for p in params]
                if current_shape != first_shape:
                    warnings_triggered.append({
                        "client_id": i,
                        "reason": "Parameter shape mismatch",
                        "expected": first_shape,
                        "received": current_shape
                    })
            
            return len(warnings_triggered) == 0
        
        #Prepare test data
        standard_params = [np.random.rand(10, 10), np.random.rand(20, 20)]
        different_params = [np.random.rand(15, 15), np.random.rand(25, 25)]
        
        #test same structure
        validate_parameters([standard_params, standard_params])
        self.assertEqual(len(warnings_triggered), 0)
        
        #test different structure
        validate_parameters([standard_params, different_params])
        self.assertEqual(len(warnings_triggered), 1)
        
        print("\n=== Warning Trigger Condition Test ===")
        if warnings_triggered:
            print(f"Warning triggered: {warnings_triggered[0]}")
        print(" Warning correctly triggered for parameter mismatch")


class ModelTypeIntegrationTest(unittest.TestCase):
    """Model type detection integration test"""
    
    def setUp(self):
        self.cfg = FLConfig(num_clients=3)
        self.strategy = UnifiedServerStrategy(self.cfg)
        
    def test_client_parameter_shape_logging(self):
        """Test client parameter shape logging"""
        shapes_log = []
        
        #Simulate receiving parameters
        def log_parameter_shapes(cid, parameters):
            shapes = [p.shape for p in parameters]
            shapes_log.append({
                "cid": cid,
                "shapes": shapes
            })
        
        #Simulate two clients
        log_parameter_shapes(1, [np.array([1, 2, 3]), np.array([[1, 2], [3, 4]])])
        log_parameter_shapes(2, [np.array([1, 2, 3]), np.array([[1, 2], [3, 4]])])
        
        #verify logging is correct
        self.assertEqual(len(shapes_log), 2)
        self.assertEqual(shapes_log[0]["shapes"], shapes_log[1]["shapes"])
        
        print("\n=== Parameter Shape Logging Test ===")
        print(f"Recorded parameter shapes: {shapes_log}")
        print(" Server correctly logs client parameter shapes")


def run_model_type_tests():
    """Run all model type tests"""
    print("\n" + "="*60)
    print("Test 1: Model Type Testing")
    print("="*60)
    
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    
    suite.addTests(loader.loadTestsFromTestCase(ModelTypeWarningTest))
    suite.addTests(loader.loadTestsFromTestCase(ModelTypeIntegrationTest))
    
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    return result.wasSuccessful()


if __name__ == "__main__":
    run_model_type_tests()