# This file was generated by team member Jiale Qin(20616174)
# Some function in this file was written by team member Mingyang Xue(20617494) Sirui Li(20617511)
import sys
import os
import ast

if __name__ == "__main__" and __package__ is None:
    _root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, _root)
    os.chdir(_root)
    import subprocess
    subprocess.run([sys.executable, "-m", "All3Feature.client"] + sys.argv[1:], check=True)
    sys.exit(0)

import argparse
from collections import OrderedDict

import flwr as fl
import numpy as np
import torch

from .config import FLConfig, build_arg_parser, config_from_args
from .utils import Net, train, test, load_data, load_data_new, get_label, DEVICE
from .features.robustness import maybe_apply_poisoning
from .features.availability import maybe_random_disconnect

def round_print(round_num):
    print('--------------------------------------------------', flush=True)
    print(f"[ROUND {round_num}]", flush=True)
    print(f"Training in progress ...", flush=True)
    print(f"[cmd] current round: {round_num}", flush=True)
    print(f"[cmd] current state: Training", flush=True)

def analysis_print(acc_iso, acc_fl):
    print(f"[ANALYSIS] >>> Isolated accuracy ={acc_iso:.4f}", flush=True)
    print(f"[ANALYSIS] >>> FL_Acc={acc_fl:.4f}", flush=True)
    print(f"[cmd] current state: Loading next round", flush=True)


class UnifiedMnistClient(fl.client.NumPyClient):
    """Client supporting poisoning, random disconnection, and optional HE."""

    def __init__(self, cid: int, label_mask: list ,cfg: FLConfig) -> None:
        self.cid = int(cid)
        self.cfg = cfg
        self.label_mask = label_mask
        self.device = DEVICE

        # Random-seed for reproducibility (per client)
        base_seed = 42 + self.cid
        import random
        random.seed(base_seed)
        np.random.seed(base_seed)
        torch.manual_seed(base_seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed(base_seed)
            torch.cuda.manual_seed_all(base_seed)
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False

        self.trainloader, self.testloader = load_data_new(self.label_mask, self.cfg.num_clients)

        self.net_fl = Net().to(self.device)
        self.net_isolated = Net().to(self.device)

        self.he = None
        self.use_he = False

        self.disconnect_prob = float(self.cfg.disconnect_prob)
        self.missed_rounds = 0

        self.is_poisoned = False

        print(
            f"[Client {self.cid}] init | "
            f"poison={self.cfg.enable_poisoning} | "
            f"random_disconnect={self.cfg.use_random_disconnection} (p={self.disconnect_prob}) | "
            f"use_he={self.cfg.use_he}", flush=True
        )

    # ---- Flower hooks ------------------------------------------------------
    def get_parameters(self, config):
        return [val.cpu().numpy() for _, val in self.net_fl.state_dict().items()]

    def set_parameters(self, net, parameters):
        params_dict = zip(net.state_dict().keys(), parameters)
        state_dict = OrderedDict({k: torch.tensor(v) for k, v in params_dict})
        net.load_state_dict(state_dict, strict=True)

    def fit(self, parameters, config):
        round_num = config.get("round", "Unknown")
        round_print(round_num=round_num)

        # Initialize HE once if enabled
        if self.he is None and config.get("use_he", False):
            try:
                from .features.privacy import init_client_he
                self.he, self.use_he = init_client_he(config, cid=self.cid)
            except ImportError as e:
                print(f"[Client {self.cid}] WARNING: Could not import privacy module: {e}. HE will be disabled.", flush=True)
                self.he = None
                self.use_he = False

        # Random disconnection path
        handled, self.missed_rounds, disconnect_result = maybe_random_disconnect(
            self.cfg,
            self.cid,
            round_num,
            self.net_isolated,
            self.trainloader,
            self.testloader,
            self.disconnect_prob,
            self.missed_rounds,
        )
        if handled:
            return disconnect_result

        # Collaborative FL path
        self.set_parameters(self.net_fl, parameters)

        # One-time poisoning for chosen client(s) via robustness feature
        self.is_poisoned = maybe_apply_poisoning(
            self.trainloader,
            self.cid,
            config.get("enable_poisoning", False),
            self.is_poisoned
        )

        # Evaluate global model before local training (proxy global accuracy)
        loss_fl, acc_fl = test(self.net_fl, self.testloader)

        # Train global FL model
        train(self.net_fl, self.trainloader, epochs=1)

        # Train isolated model
        train(self.net_isolated, self.trainloader, epochs=1)
        loss_iso, acc_iso = test(self.net_isolated, self.testloader)
        analysis_print(acc_iso= acc_iso, acc_fl=acc_fl)

        updated_params = self.get_parameters(config={})

        # Delegate HE or plain upload to privacy feature helper
        if self.use_he and self.he is not None:
            try:
                from .features.privacy import encrypt_client_update
                return encrypt_client_update(
                    updated_params,
                    self.he,
                    self.use_he,
                    cid=self.cid,
                    num_examples=len(self.trainloader.dataset),
                    metrics={
                        "cid": self.cid,
                        "disconnected": False,
                        "isolated_accuracy": float(acc_iso),
                        "fl_accuracy": float(acc_fl),
                    },
                    config=config,
                )
            except ImportError as e:
                print(f"[Client {self.cid}] WARNING: Could not import privacy module: {e}. Falling back to plain upload.", flush=True)
                self.use_he = False
        
        # Plain upload (no HE)
        return updated_params, len(self.trainloader.dataset), {
            "cid": self.cid,
            "disconnected": False,
            "isolated_accuracy": float(acc_iso),
            "fl_accuracy": float(acc_fl),
        }

    def evaluate(self, parameters, config):
        self.set_parameters(self.net_fl, parameters)
        loss, accuracy = test(self.net_fl, self.testloader)
        return float(loss), len(self.testloader.dataset), {"accuracy": float(accuracy)}


def build_client_arg_parser() -> argparse.ArgumentParser:
    parser = build_arg_parser()
    parser.description = "Unified Flower + MNIST client"
    parser.add_argument("--cid", type=int, required=True, help="Client ID (1..num_clients)")
    parser.add_argument("--label", type=str, help="Label mask as list e.g., [0,1,0,0,0,0,0,0,0,0]")
    return parser

def mask_to_labels(label_mask):
    return [i for i, val in enumerate(label_mask) if val == 1]


def main():
    parser = build_client_arg_parser()
    args = parser.parse_args()
    cfg = config_from_args(args)
    
    cid = args.cid
    print(f"Starting unified client {cid} connecting to {cfg.server_address}", flush=True)

    if args.label:
        label_mask = list(ast.literal_eval(args.label))
        active_labels = mask_to_labels(label_mask)
        # If no labels selected (e.g. UI sent all zeros), fall back to default split
        if not active_labels:
            print("No labels selected; using default label split for this client", flush=True)
            label_mask = get_label(cid, cfg.num_clients)
            active_labels = mask_to_labels(label_mask)
        print(f"Using label: {active_labels}", flush=True)
    else:
        label_mask = get_label(cid, cfg.num_clients)

    client = UnifiedMnistClient(cid, label_mask, cfg)
    fl.client.start_client(
        server_address=cfg.server_address,
        client=client.to_client(),
    )


if __name__ == "__main__":
    main()

