# This file was generated by team member Jiale Qin(20616174)
import argparse
from dataclasses import dataclass

from .defaults import (
    NUM_CLIENTS,
    NUM_ROUNDS,
    USE_HE,
    USE_DEFENSE,
    USE_RANDOM_DISCONNECTION,
    USE_HISTORY_UPDATES,
    ENABLE_POISONING,
)


@dataclass
class FLConfig:
    """Runtime configuration for the unified FL system."""

    # Core FL settings
    num_clients: int = NUM_CLIENTS
    num_rounds: int = NUM_ROUNDS
    server_address: str = "0.0.0.0:8080"

    # Features
    use_he: bool = USE_HE
    use_defense: bool = USE_DEFENSE
    use_random_disconnection: bool = USE_RANDOM_DISCONNECTION
    use_history_updates: bool = USE_HISTORY_UPDATES
    enable_poisoning: bool = ENABLE_POISONING  # label-flip attack on a chosen client

    # Random-disconnection / historical update parameters
    disconnect_prob: float = 0.0
    max_stale_rounds: int = 5

    # Defense (MAD + reputation) parameters
    defense_sigma: float = 2.0
    trust_ema_alpha: float = 0.7

    # HE parameters (mirrors flower_privacy defaults)
    he_encrypt_ratio: float = 0.02
    he_mask_seed: int = 42


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Unified Flower + MNIST FL system with poisoning+defense, "
        "random disconnection+historical updates, and partial HE."
    )

    # Core
    parser.add_argument("--num-clients", type=int, default=NUM_CLIENTS)
    parser.add_argument("--num-rounds", type=int, default=NUM_ROUNDS)
    parser.add_argument("--server-address", type=str, default="0.0.0.0:8080")

    # Feature toggles
    parser.add_argument("--use-he", action="store_true", default=USE_HE)
    parser.add_argument(
        "--use-defense", action="store_true", default=USE_DEFENSE
    )
    parser.add_argument(
        "--use-random-disconnection",
        action="store_true",
        default=USE_RANDOM_DISCONNECTION,
    )
    parser.add_argument(
        "--use-history-updates",
        action="store_true",
        default=USE_HISTORY_UPDATES,
    )
    parser.add_argument(
        "--enable-poisoning",
        action="store_true",
        default=ENABLE_POISONING,
    )

    # Random-disconnection settings
    parser.add_argument("--disconnect-prob", type=float, default=0.0)
    parser.add_argument("--max-stale-rounds", type=int, default=5)

    # Defense params
    parser.add_argument("--defense-sigma", type=float, default=2.0)
    parser.add_argument("--trust-ema-alpha", type=float, default=0.7)

    # HE params
    parser.add_argument("--he-encrypt-ratio", type=float, default=0.02)
    parser.add_argument("--he-mask-seed", type=int, default=42)

    return parser


def config_from_args(args: argparse.Namespace) -> FLConfig:
    return FLConfig(
        num_clients=args.num_clients,
        num_rounds=args.num_rounds,
        server_address=args.server_address,
        use_he=args.use_he,
        use_defense=args.use_defense,
        use_random_disconnection=args.use_random_disconnection,
        use_history_updates=args.use_history_updates,
        enable_poisoning=args.enable_poisoning,
        disconnect_prob=args.disconnect_prob,
        max_stale_rounds=args.max_stale_rounds,
        defense_sigma=args.defense_sigma,
        trust_ema_alpha=args.trust_ema_alpha,
        he_encrypt_ratio=args.he_encrypt_ratio,
        he_mask_seed=args.he_mask_seed,
    )

