# This file was generated by team member Jiale Qin(20616174)
"""Manual runtime defaults.

These defaults are used when you don't pass CLI flags.
CLI flags (e.g. --use-he) will override these defaults.
"""

# --- Core runtime defaults (edit here) ---
NUM_CLIENTS = 8
NUM_ROUNDS = 30

# --- Core feature toggles (defaults) ---
USE_HE = False
USE_DEFENSE = False
ENABLE_POISONING = False
USE_RANDOM_DISCONNECTION = False
USE_HISTORY_UPDATES = False

