"""
Paillier partial homomorphic encryption utilities for federated learning.
"""

# This file was generated by team member Jiale Qin(20616174)
import pickle
import base64
from typing import List, Tuple, Optional

import numpy as np
from phe import paillier
from flwr.common import ndarrays_to_parameters  # used by server-side code


class PaillierHE:
    """Wrapper around python-paillier for partial encryption in FL."""

    def __init__(self, key_size: int = 1024) -> None:
        self.public_key, self._private_key = paillier.generate_paillier_keypair(
            n_length=key_size
        )

    def encrypt_value(self, value: float) -> paillier.EncryptedNumber:
        return self.public_key.encrypt(float(value))

    def decrypt_value(self, enc: paillier.EncryptedNumber) -> float:
        return self._private_key.decrypt(enc)

    def decrypt_parameters_partial(
        self,
        mixed_layers: List[list],
        masks: List[np.ndarray],
    ) -> List[np.ndarray]:
        """Decrypt aggregated parameters: encrypted positions are decrypted,
        plain positions are kept as-is."""
        result = []
        for layer_flat, mask in zip(mixed_layers, masks):
            out = np.zeros(len(layer_flat), dtype=np.float64)
            for i, val in enumerate(layer_flat):
                if mask[i]:
                    out[i] = self._private_key.decrypt(val)
                else:
                    out[i] = float(val)
            result.append(out)
        return result


def generate_encryption_masks(
    params: List[np.ndarray],
    encrypt_ratio: float = 0.02,
    seed: int = 42,
) -> List[np.ndarray]:
    """Generate boolean masks indicating which flattened positions to encrypt."""
    rng = np.random.RandomState(seed)
    masks = []
    for p in params:
        size = p.size
        n_encrypt = max(1, int(size * encrypt_ratio))
        mask = np.zeros(size, dtype=bool)
        indices = rng.choice(size, n_encrypt, replace=False)
        mask[indices] = True
        masks.append(mask)
    return masks


def _serialize_layer(
    flat: np.ndarray,
    mask: np.ndarray,
    public_key: paillier.PaillierPublicKey,
    shape: tuple,
) -> dict:
    """Serialize one layer: encrypt masked positions, keep rest as plain floats."""
    encrypted = []
    for i, val in enumerate(flat):
        if mask[i]:
            encrypted.append(public_key.encrypt(float(val)))
        else:
            encrypted.append(float(val))
    return {"shape": shape, "data": encrypted}


def deserialize_partial_encrypted_parameters(
    serialized_params: List[dict],
    masks: List[np.ndarray],
) -> List[list]:
    """Extract the flat mixed (encrypted + plain) list from serialized dicts."""
    return [sp["data"] for sp in serialized_params]


def secure_aggregate_partial_encrypted(
    all_client_params: List[List[list]],
    num_examples_list: List[int],
    public_key: paillier.PaillierPublicKey,
    masks: List[np.ndarray],
) -> List[list]:
    """Weighted sum across clients on mixed encrypted/plain parameters.
    Paillier supports: ciphertext + ciphertext, and ciphertext * plaintext scalar."""
    num_layers = len(all_client_params[0])
    aggregated = []

    for layer_idx in range(num_layers):
        layer_size = len(all_client_params[0][layer_idx])
        agg_layer: list = []

        for pos in range(layer_size):
            acc = None
            for client_idx, client_params in enumerate(all_client_params):
                w = float(num_examples_list[client_idx])
                val = client_params[layer_idx][pos]
                weighted = val * w
                if acc is None:
                    acc = weighted
                else:
                    acc = acc + weighted
            agg_layer.append(acc)

        aggregated.append(agg_layer)

    return aggregated


def init_he_from_config(config: dict, client_id: int):
    """Client-side HE initialization: recover public key from server config."""
    he_pub_key_str = config.get("he_public_key", "")
    if not he_pub_key_str:
        return None, False

    pub_key = pickle.loads(base64.b64decode(he_pub_key_str.encode("utf-8")))
    print(f"[Client {client_id}] HE public key received, encryption enabled.")
    return pub_key, True


def encrypt_and_return_params(
    updated_params: List[np.ndarray],
    he_public_key,
    use_he: bool,
    client_id: int,
    num_examples: int,
    metrics: dict,
    config: dict,
):
    """Encrypt (partially) the client model update and return Flower-compatible result."""
    if not use_he or he_public_key is None:
        return updated_params, num_examples, metrics

    encrypt_ratio = config.get("he_encrypt_ratio", 0.02)
    mask_seed = config.get("he_mask_seed", 42)

    masks = generate_encryption_masks(updated_params, encrypt_ratio, mask_seed)

    serialized = []
    for layer, mask in zip(updated_params, masks):
        flat = layer.flatten().astype(np.float64)
        ser = _serialize_layer(flat, mask, he_public_key, layer.shape)
        serialized.append(pickle.dumps(ser))

    param_arrays = [np.frombuffer(s, dtype=np.uint8).copy() for s in serialized]

    print(f"[Client {client_id}] Partial HE encryption done (ratio={encrypt_ratio}).")
    return param_arrays, num_examples, metrics
