"""
Drawing tool module. Referring to the plot_utils of flower_privacy, it is only responsible for visualization and does not participate in the training/aggregation logic.
"""

# This file was generated by team member Xinchen Dai(20616310)
# Some function in this file was written by team member Mingyang Xue(20617494)
import os
import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


TARGET_FOLDER = "image_folder\images_mnist"
HISTORY_FILE_HE = os.path.join(TARGET_FOLDER, "history_with_he.json")
HISTORY_FILE_NO_HE = os.path.join(TARGET_FOLDER, "history_without_he.json")

#Robustness specific file paths
HISTORY_FILE_BASIC = os.path.join(TARGET_FOLDER, "history_basic.json")
HISTORY_FILE_ATTACK_NO_DEF = os.path.join(TARGET_FOLDER, "history_attack_no_def.json")
HISTORY_FILE_ATTACK_DEF = os.path.join(TARGET_FOLDER, "history_attack_def.json")

def save_history(history: dict, use_he: bool = False, enable_poisoning: bool = False, use_defense: bool = False,target_folder: str = TARGET_FOLDER) -> None:
    """Save history to JSON."""
    if not os.path.exists(target_folder):
        os.makedirs(target_folder)

    #Determine the correct filename based on the current run's flags
    if use_he:
        filename = "history_with_he.json"
    elif enable_poisoning and use_defense:
        filename = "history_attack_def.json"
    elif enable_poisoning and not use_defense:
        filename = "history_attack_no_def.json"
    elif use_defense and not enable_poisoning:
        filename = "history_def_no_attack.json"  # Just in case this edge case is run
    else:
        #If no HE, no attack, and no defense, it's the baseline
        filename = "history_basic.json"

    #path = HISTORY_FILE_HE if use_he else HISTORY_FILE_NO_HE
    #path = os.path.join(target_folder, os.path.basename(path))
    path = os.path.join(target_folder, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2, ensure_ascii=False)
    print(f"[SERVER] History saved to {path}")


# def load_history(use_he: bool, target_folder: str = TARGET_FOLDER):
#     """Load saved history (for comparison plots)."""
#     path = os.path.join(target_folder, "history_with_he.json" if use_he else "history_without_he.json")
#     if os.path.exists(path):
#         with open(path, "r", encoding="utf-8") as f:
#             return json.load(f)
#     return None

def load_history(filepath: str):
    """Generic history loading helper function."""
    if os.path.exists(filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            return json.load(f)
    return None

def plot_robustness_comparison(target_folder: str = TARGET_FOLDER) -> None:
    """Three-line comparison plot specifically for robustness testing (global accuracy)."""
    if not os.path.exists(target_folder):
        return

    plt.figure(figsize=(10, 6))
    lines_plotted = 0

    #No attack, no defense (Baseline)
    hist_basic = load_history(os.path.join(target_folder, "history_basic.json"))
    if hist_basic and hist_basic.get("rounds") and hist_basic.get("global_acc"):
        plt.plot(hist_basic["rounds"], hist_basic["global_acc"],
                 color="green", linewidth=2, marker="o",
                 label="{No Attack, No Defense}")
        lines_plotted += 1

    #Attack, no defense
    hist_attack_no_def = load_history(os.path.join(target_folder, "history_attack_no_def.json"))
    if hist_attack_no_def and hist_attack_no_def.get("rounds") and hist_attack_no_def.get("global_acc"):
        plt.plot(hist_attack_no_def["rounds"], hist_attack_no_def["global_acc"],
                 color="red", linewidth=2, marker="x", linestyle="--",
                 label="{Attack, No Defense}")
        lines_plotted += 1

    # Attack, defense
    hist_attack_def = load_history(os.path.join(target_folder, "history_attack_def.json"))
    if hist_attack_def and hist_attack_def.get("rounds") and hist_attack_def.get("global_acc"):
        plt.plot(hist_attack_def["rounds"], hist_attack_def["global_acc"],
                 color="blue", linewidth=2, marker="*",
                 label="{Attack, Defense}")
        lines_plotted += 1

    if lines_plotted > 0:
        plt.title("Federated Learning Robustness: Global Accuracy Under Poisoning Attack")
        plt.xlabel("Round")
        plt.ylabel("Global Accuracy")
        plt.ylim(0, 1.05)
        plt.legend(bbox_to_anchor=(1.04, 1), loc="upper left")
        plt.tight_layout()
        plt.grid(True)
        out = os.path.join(target_folder, "mnist_robustness_comparison.png")
        plt.savefig(out, bbox_inches="tight")
        plt.close()
        print(f"[SERVER] Robustness comparison plot saved to {out}")
    else:
        plt.close()


def plot_fl_vs_isolated(
        history: dict,
        use_he : bool = False,
        use_availability: bool = False,
        enable_poisoning: bool = False,
        use_defense: bool = False,
        target_folder: str = TARGET_FOLDER) -> None:
    """Federated learning global model plot."""
    if not history.get("rounds") or not history.get("global_acc"):
        print("[SERVER] No rounds/global_acc in history, skip FL vs isolated plot.")
        return
    if not os.path.exists(target_folder):
        os.makedirs(target_folder)

    #Precisely determine the suffix, ensuring one-to-one correspondence with the JSON names generated by save_history
    if use_he:
        suffix = "with_he"
        title_mode = "Privacy"
    elif use_availability:
        suffix = "availability"
        title_mode = "Availability"
    elif enable_poisoning and use_defense:
        suffix = "attack_def"
        title_mode = "Robustness (Attack + Defense)"
    elif enable_poisoning and not use_defense:
        suffix = "attack_no_def"
        title_mode = "Robustness (Attack Only)"
    elif use_defense and not enable_poisoning:
        suffix = "def_no_attack"
        title_mode = "Robustness (Defense Only)"
    else:
        suffix = "basic"
        title_mode = "Basic"


    plt.figure(figsize=(10, 6))
    plt.plot(
        history["rounds"], history["global_acc"],
        color="black", linewidth=3, marker="*", markersize=10,
        label="Global FL Model (Aggregated)",
    )

    plt.title(f"Federated Learning ({title_mode} Mode)")
    plt.xlabel("Round")
    plt.ylabel("Accuracy")
    plt.ylim(0, 1.0)
    plt.legend(bbox_to_anchor=(1.04, 1), loc="upper left")
    plt.tight_layout()
    plt.grid(True)
    out = os.path.join(target_folder, f"plot_{suffix}.png")
    plt.savefig(out, bbox_inches="tight")
    plt.close()
    print(f"[SERVER] Plot saved to {out}")


def plot_he_comparison(current_history: dict, use_he: bool, target_folder: str = TARGET_FOLDER) -> None:
    """Global accuracy comparison with HE / without HE (if the other history exists)."""
    if not use_he:
        other_path = os.path.join(target_folder, "history_with_he.json")
    else:
        other_path = os.path.join(target_folder, "history_basic.json")
    other_history = load_history(other_path)
    plt.figure(figsize=(10, 6))

    he_history = current_history if use_he else other_history
    if he_history and he_history.get("rounds") and he_history.get("global_acc"):
        plt.plot(
            he_history["rounds"], he_history["global_acc"],
            color="blue", linewidth=3, marker="*", markersize=10,
            linestyle="--", label="Global Model (With HE)",
        )
    no_he_history = current_history if not use_he else other_history
    if no_he_history and no_he_history.get("rounds") and no_he_history.get("global_acc"):
        plt.plot(
            no_he_history["rounds"], no_he_history["global_acc"],
            color="red", linewidth=3, marker="o", markersize=10,
            label="Global Model (Without HE)",
        )

    if he_history and no_he_history and he_history.get("global_acc") and no_he_history.get("global_acc"):
        plt.title("Federated Learning: With HE vs Without HE (Accuracy Comparison)")
    elif he_history and he_history.get("global_acc"):
        plt.title("Federated Learning: Global Model Accuracy (With HE)")
    elif no_he_history and no_he_history.get("global_acc"):
        plt.title("Federated Learning: Global Model Accuracy (Without HE)")
    else:
        plt.title("Federated Learning: Global Model Accuracy")
    plt.xlabel("Round")
    plt.ylabel("Accuracy")
    plt.ylim(0, 1.0)
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.grid(True)
    out = os.path.join(target_folder, "mnist_he_comparison.png")
    plt.savefig(out, bbox_inches="tight")
    plt.close()
    print(f"[SERVER] HE comparison plot saved to {out}")


def plot_history_updates_comparison(history: dict, target_folder: str = TARGET_FOLDER) -> None:
    """Plot accuracy comparison between using history updates and not using history updates."""
    if not history.get("rounds") or not history.get("global_acc") or not history.get("global_acc_no_history"):
        print("[SERVER] No rounds/global_acc/global_acc_no_history in history, skip history updates comparison plot.")
        return
    if not os.path.exists(target_folder):
        os.makedirs(target_folder)

    plt.figure(figsize=(10, 6))
    
    #Plot with history updates
    plt.plot(
        history["rounds"], history["global_acc"],
        color="blue", linewidth=3, marker="*", markersize=10,
        label="With History Updates",
    )
    
    #Plot without history updates
    plt.plot(
        history["rounds"], history["global_acc_no_history"],
        color="red", linewidth=3, marker="o", markersize=10,
        label="Without History Updates",
    )

    plt.title("Federated Learning: With History Updates vs Without History Updates")
    plt.xlabel("Round")
    plt.ylabel("Accuracy")
    plt.ylim(0, 1.0)
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.grid(True)
    out = os.path.join(target_folder, "mnist_history_updates_comparison.png")
    plt.savefig(out, bbox_inches="tight")
    plt.close()
    print(f"[SERVER] History updates comparison plot saved to {out}")


def plot_all_results(
        history: dict,
        use_he: bool = False,
        use_availability: bool = False,
        use_defense: bool = False,
        enable_poisoning: bool = False,
        target_folder: str = TARGET_FOLDER
) -> None:
    """Save history and generate all plots (FL vs isolated + optional HE comparison)."""
    save_history(history, use_he, enable_poisoning, use_defense, target_folder)

    #Generate single-line plot (pass all boolean parameters as-is, let it determine the name itself)
    plot_fl_vs_isolated(
        history=history,
        use_he=use_he,
        use_availability=use_availability,
        enable_poisoning=enable_poisoning,
        use_defense=use_defense,
        target_folder=target_folder
    )


    # # Determine feature type
    # if use_he:
    #     feature_type = "privacy"
    # elif use_availability:
    #     feature_type = "availability"
    # elif use_robustness:
    #     feature_type = "robustness"
    # else:
    #     feature_type = "basic"
    #
    # plot_fl_vs_isolated(history, feature_type, target_folder)
    #Only draw HE comparison plot when using HE
    if use_he:
        plot_he_comparison(history, use_he, target_folder)
    #Only draw robustness three-line comparison plot when doing robustness experiments
    if use_defense or enable_poisoning:
        plot_robustness_comparison(target_folder)
    #Only draw history updates comparison plot when both experiments have been run
    if history.get("global_acc_no_history"):
        plot_history_updates_comparison(history, target_folder)
