# This file was generated by team member Sirui LI(20617511)
import json
import os
import re

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def _history_is_valid(h):
    """Need non-empty rounds and global_acc (empty list [] is falsy — do not use `if h.get('global_acc')` alone)."""
    if not h or not isinstance(h, dict):
        return False
    ra = h.get('rounds')
    ga = h.get('global_acc')
    return isinstance(ra, list) and isinstance(ga, list) and len(ra) > 0 and len(ga) > 0


def _iter_log_entries(content: str):
    """
    Yield top-level JSON objects from simulator log text.

    Supports:
    - JSONL (one compact object per line)
    - Concatenated pretty-printed objects ``{ ... }{ ... }`` (multi-line each)
    """
    decoder = json.JSONDecoder()
    idx = 0
    n = len(content)
    while idx < n:
        while idx < n and content[idx].isspace():
            idx += 1
        if idx >= n:
            break
        try:
            entry, end = decoder.raw_decode(content, idx)
            yield entry
            idx = end
        except json.JSONDecodeError:
            idx += 1


def parse_last_plot_history_from_simulator_log(filepath):
    """
    Read a simulator log and return the best history dict from ``[cmd][plot]`` entries.

    Chooses the entry with the longest ``global_acc`` (most complete training curve).
    Works for both JSONL and multi-line pretty-printed logs.
    """
    if not os.path.isfile(filepath):
        return None
    best_history = None
    best_len = -1
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    for entry in _iter_log_entries(content):
        if not isinstance(entry, dict):
            continue
        data = entry.get('data', '')
        if '[cmd][plot]' not in data:
            continue
        m = re.search(r'\[cmd\]\[plot\]\s*total_rounds:\s*\d+\s*,\s*(.+)', data, re.DOTALL)
        if not m:
            continue
        json_str = m.group(1).strip()
        if json_str.endswith('\n'):
            json_str = json_str.rstrip('\n')
        try:
            hist = json.loads(json_str)
        except json.JSONDecodeError:
            continue
        if not _history_is_valid(hist):
            continue
        acc_len = len(hist.get('global_acc', []))
        if acc_len > best_len:
            best_len = acc_len
            best_history = hist
    return best_history


# Simulator filenames + legend labels for robustness compare (static PNG + JSON API).
ROBUSTNESS_SIMULATOR_FILES = [
    ('robustness_noattack_nodefense.json', '(No attack No defense)'),
    ('robustness_attack_nodefense.json', '(Attack No Defense)'),
    ('robustness_attack_with_defense.json', '(Attack with Defense)'),
]


def build_robustness_compare_series(log_dir):
    """
    Load optional simulator logs. Returns (series, max_round_cap).

    Each item in series: ``{'label': str, 'rounds': [int, ...], 'global_acc': [float, ...]}``
    (``global_acc`` in 0..1).
    """
    series = []
    max_r = 30
    for fname, label in ROBUSTNESS_SIMULATOR_FILES:
        path = os.path.join(log_dir, fname)
        if not os.path.isfile(path):
            continue
        h = parse_last_plot_history_from_simulator_log(path)
        if not h or not _history_is_valid(h):
            continue
        rounds = h['rounds']
        acc = h['global_acc']
        n = min(len(rounds), len(acc))
        rounds = rounds[:n]
        acc = acc[:n]
        series.append(
            {
                'label': label,
                'rounds': [int(r) for r in rounds],
                'global_acc': [float(a) for a in acc],
            }
        )
        if rounds:
            max_r = max(max_r, max(int(r) for r in rounds))
    return series, max_r


class PlotGraph:
    def __init__(self, max_rounds):
        self.max_rounds = max_rounds
        
    def plot(self, history_data, plot_path=None):
        rounds = []
        acc = []
        acc_no_history = []
        client_accs = {} 
        plt.close('all')
        
        # Use provided history data instead of loading from file
        if history_data.get('rounds') and history_data.get('global_acc'):
            rounds = history_data['rounds']
            acc = [a * 100 for a in history_data['global_acc']]
            
            # Check if we have no_history data (availability mode)
            if history_data.get('global_acc_no_history'):
                acc_no_history = [a * 100 for a in history_data['global_acc_no_history']]
        
        # Prepare client data (skip if skip_client_acc is True, e.g. for robustness simulate)
        skip_client_acc = history_data.get('_skip_client_acc', False)
        if not skip_client_acc:
            client_accs = self._prepare_client_data(history_data, rounds)
        
        # Plot
        plt.figure(figsize=(12, 7))
        has_history_comparison = bool(acc_no_history)
        main_label = 'Global FL Model (with history)' if has_history_comparison else 'Global FL Model'
        plt.plot(rounds, acc, 'bo-', linewidth=3, markersize=8, label=main_label)
        
        # Plot no_history line only for availability comparison mode
        if acc_no_history:
            plt.plot(rounds, acc_no_history, 'ro-', linewidth=3, markersize=8, label='Global FL Model (without history)')
        
        # Plot client isolated accuracies (skip for robustness simulate)
        if not skip_client_acc and client_accs:
            colors = [
                '#e41a1c',  # red
                '#4daf4a',  # green
                '#984ea3',  # purple
                '#ff7f00',  # orange
                '#ffff33',  # yellow
                '#a65628',  # brown
                '#f781bf',  # pink
                '#999999',  # gray
                '#66c2a5',  # teal
                '#fc8d62',  # coral
                '#8da0cb',  # lavender
                '#e78ac3',  # magenta
                '#a6d854',  # lime
                '#ffd92f',  # gold
                '#e5c494',  # beige
                '#b3b3b3'   # light gray
            ]
            for idx, (client_id, client_acc) in enumerate(client_accs.items()):
                rounds_data, acc_data = client_acc
                plt.plot(rounds_data, acc_data,
                        color=colors[idx % len(colors)], 
                        linestyle='--', 
                        linewidth=2, 
                        marker='o', 
                        markersize=4,
                        label=f'Client {client_id}')
            
        # Add annotations for with history data
        for r, a in zip(rounds, acc):
            plt.annotate(f'{a:.1f}%', 
                    (r, a), 
                    textcoords="offset points", 
                    xytext=(0, 10),
                    ha='center',
                    fontsize=8,
                    bbox=dict(boxstyle="round,pad=0.2", facecolor="white", alpha=0.7))
        
        # Add annotations for without history data
        if acc_no_history:
            for r, a in zip(rounds, acc_no_history):
                plt.annotate(f'{a:.1f}%', 
                        (r, a), 
                        textcoords="offset points", 
                        xytext=(0, -20),
                        ha='center',
                        fontsize=8,
                        bbox=dict(boxstyle="round,pad=0.2", facecolor="white", alpha=0.7))
        
        plt.xlim(0, self.max_rounds)
        plt.ylim(0, 110)
        plt.xlabel('Round', fontsize=12)
        plt.ylabel('Accuracy (%)', fontsize=12)
        plt.title(f'Training Progress ({rounds[-1]} / {self.max_rounds} rounds)', fontsize=14)
        plt.grid(True, alpha=0.3)
        plt.legend(loc='lower right')
        
        # Save plot
        if plot_path:
            os.makedirs(os.path.dirname(plot_path), exist_ok=True)
            plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        
        plt.close()
        return plot_path
    
    def _prepare_client_data(self, data, rounds):
        """Prepare client accuracy data - only include rounds where client actually participated"""
        client_accs = {}
        
        # Get client participation data
        client_participation = data.get('client_active_rounds', {})
        
        # Build client accuracy arrays
        if data.get('client_isolated_acc'):
            for client_id, acc_list in data['client_isolated_acc'].items():
                valid_rounds = []
                valid_acc = []
                
                # Get rounds this client participated in
                if client_id in client_participation:
                    active_rounds = client_participation[client_id]
                    
                    # Only include rounds where client actually participated
                    for i, round_num in enumerate(active_rounds):
                        if i < len(acc_list):
                            valid_rounds.append(round_num)
                            valid_acc.append(acc_list[i] * 100)
                
                if valid_rounds:
                    client_accs[client_id] = (valid_rounds, valid_acc)
        
        return client_accs


def plot_robustness_compare(histories, labels, max_rounds_cap, plot_path=None):
    """
    Plot one or more global accuracy curves vs round (same x = training round index).

    histories: list of dicts with 'rounds' and 'global_acc'
    labels: legend strings (same length as histories)
    max_rounds_cap: x-axis upper bound
    """
    plt.close('all')
    plt.figure(figsize=(12, 7))

    # (color, linestyle, marker) — cycle if more than three series
    styles = [
        ('#2ca02c', '-', 'o'),   # green solid
        ('#d62728', '--', 's'),  # red dashed
        ('#1f77b4', '-.', '^'),  # blue dash-dot
    ]

    max_round_seen = 0
    any_plotted = False

    for i, (hist, label) in enumerate(zip(histories, labels)):
        color, ls, marker = styles[i % len(styles)]
        if not hist or not hist.get('rounds') or not hist.get('global_acc'):
            continue
        rounds = hist['rounds']
        acc = [float(a) * 100.0 for a in hist['global_acc']]
        if len(rounds) != len(acc):
            n = min(len(rounds), len(acc))
            rounds = rounds[:n]
            acc = acc[:n]
        if not rounds:
            continue
        max_round_seen = max(max_round_seen, max(rounds))
        plt.plot(
            rounds,
            acc,
            color=color,
            linestyle=ls,
            marker=marker,
            linewidth=2.5,
            markersize=6,
            label=label,
        )
        any_plotted = True

    if not any_plotted:
        plt.text(0.5, 0.5, 'No data', ha='center', va='center', transform=plt.gca().transAxes)
        plt.xlabel('Round', fontsize=12)
        plt.ylabel('Accuracy (%)', fontsize=12)
        plt.title('Robustness comparison', fontsize=14)
    else:
        plt.xlim(0, max(max_rounds_cap, max_round_seen, 1))
        plt.ylim(0, 110)
        plt.xlabel('Round', fontsize=12)
        plt.ylabel('Accuracy (%)', fontsize=12)
        plt.title('Robustness comparison (global accuracy vs round)', fontsize=14)
        plt.grid(True, alpha=0.3)
        plt.legend(loc='lower right')

    if plot_path:
        os.makedirs(os.path.dirname(plot_path) or '.', exist_ok=True)
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')

    plt.close()
    return plot_path


# Usage / Testing 
# save_dir = 'static'
# save_path = os.path.join(save_dir, 'training_plot.png')
# log_file = os.path.join('logs', 'training_log.json')
# PlotGraph(max_rounds=10).plot(log_file, plot_path=save_path)