"""Unified FL server. Run from project root: python -m All3Feature.server
or run this file directly: python server.py (it will automatically rerun as a module)
"""
# This file was generated by team member Jiale Qin(20616174)
# Some function in this file was written by team member Mingyang Xue(20617494) Sirui Li(20617511)
import sys
import os
from argon2 import Parameters
import json

if __name__ == "__main__" and __package__ is None:
    _root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, _root)
    os.chdir(_root)
    import subprocess
    subprocess.run([sys.executable, "-m", "All3Feature.server"] + sys.argv[1:], check=True)
    sys.exit(0)

import time
from typing import Dict, List, Tuple, Callable

import numpy as np
import flwr as fl
from flwr.common import ndarrays_to_parameters, parameters_to_ndarrays, FitIns

from .config import FLConfig, build_arg_parser, config_from_args
from .utils import Net, test, DEVICE
from .features.robustness import aggregate_with_mad_reputation
from .features.availability import build_weight_results_with_history
from .plot_utils import plot_all_results
from torchvision.datasets import MNIST
from torchvision.transforms import Compose, ToTensor, Normalize
from torch.utils.data import DataLoader
from collections import OrderedDict
import torch

def get_evaluate_fn():

    data_dir = "./back_end/All3Feature/data"  # default
    tr = Compose([ToTensor(),Normalize((0.1307,),(0.3081,))])
    testset = MNIST(data_dir,train=False,download=True,transform=tr)
    testloader = DataLoader(testset,batch_size=32,shuffle=False)

    def evaluate(server_round,parameters,config):
        net=Net().to(DEVICE)
        params_dict = zip(net.state_dict().keys(),parameters)
        state_dict = OrderedDict({k:torch.tensor(v) for k,v in params_dict})
        net.load_state_dict(state_dict,strict=True)

        loss,accuracy = test(net,testloader)
        return float(loss),{"accuracy":float(accuracy)}
    return evaluate

# Get current timestamp in seconds
def get_timestamp_seconds():
    return int(time.time())

def print_start_load(server_round, desired_clients, clients_num):
    print('--------------------------------------------------', flush=True) # Flush
    print(f"[LOADING] - Round {server_round}", flush=True)
    print(f"[LOADING] - Desired clients number: ({desired_clients})", flush=True)
    print(f"[LOADING] - Connected clients number: ({clients_num} out of {desired_clients})", flush=True)
    print(f"[cmd] current state: Loading clients", flush=True)

def print_loading(clients_num, desired_clients):
    print(f"[LOADING] - Connected clients number: ({clients_num} out of {desired_clients})", flush=True)
    print(f"[cmd] current client number: {clients_num}", flush=True)

def print_training(server_round, clients_num, desired_clients, current_state = "Training"):
    print(f"[ROUND {server_round}]", flush=True)
    print(f"Active clients this round: {clients_num} / {desired_clients}")
    print(f"Training in progress ...", flush=True)
    print(f"[cmd] current round: {server_round}", flush=True)
    print(f"[cmd] current client number: {clients_num}", flush=True)
    print(f"[cmd] current state: {current_state}", flush=True)


def print_evalute(server_round, metrics, loss):
    print(f"--- Round {server_round} Analysis ---", flush=True)
    print(f"[ANALYSIS] >>> Global model accuracy: {metrics['accuracy']:.4f}", flush=True)
    print(f"[ANALYSIS] >>> Global model loss: {loss:.4f}", flush=True)

def flconfig_to_dict(cfg):
    """Convert FLConfig object to JSON-serializable dictionary"""
    return {
        'num_clients': cfg.num_clients,
        'num_rounds': cfg.num_rounds,
        'server_address': cfg.server_address,
        'use_he': cfg.use_he,
        'use_defense': cfg.use_defense,
        'use_random_disconnection': cfg.use_random_disconnection,
        'use_history_updates': cfg.use_history_updates,
        'enable_poisoning': cfg.enable_poisoning,
        'disconnect_prob': cfg.disconnect_prob,
        'max_stale_rounds': cfg.max_stale_rounds,
        'defense_sigma': cfg.defense_sigma,
        'trust_ema_alpha': cfg.trust_ema_alpha,
        'he_encrypt_ratio': cfg.he_encrypt_ratio,
        'he_mask_seed': cfg.he_mask_seed
    }

class UnifiedServerStrategy(fl.server.strategy.Strategy):
    """Unified server strategy with optional HE, defense, and historical updates."""

    def send_data(self):
        print(f"[cmd][data] {json.dumps(self.history)}", flush=True)
        print(f"[cmd][plot] total_rounds: {self.cfg.num_rounds}, {json.dumps(self.history)}", flush=True)

    def __init__(self, cfg: FLConfig, evaluate_fn: Callable | None = None) -> None:
        self.cfg = cfg
        self.evaluate_fn = evaluate_fn
        self.previous_parameters = None
        self.previous_parameters_no_history = None  # For no history updates experiment
        self.he = None
        self.previous_time = get_timestamp_seconds()

        # Only import and initialize HE if needed
        if cfg.use_he:
            try:
                from .features.privacy import init_server_he
                self.he = init_server_he(cfg)
            except ImportError as e:
                print(f"[WARNING] Could not import privacy module: {e}. HE will be disabled.")
                self.cfg.use_he = False

        # Check if we need to run both experiments (with and without history updates)
        self.run_both_experiments = cfg.use_random_disconnection and cfg.use_history_updates

        self.history: Dict[str, dict] = {
            "rounds": [],
            "client_isolated_acc": {},
            "client_active_rounds": {},
            "global_acc": [],
            "global_acc_no_history": [],  # For no history updates experiment
            "total_time": []
        }

        # For random disconnection + historical updates
        self.client_latest_updates: Dict[int, dict] = {}
        self.client_last_active_round: Dict[int, int] = {}

        # For defense (MAD + reputation)
        self.client_trusts: Dict[int, float] = {}
        self.client_trust_history: Dict[int, List[float]] = {}

    # ---- Core Flower hooks -------------------------------------------------
    def initialize_parameters(self, client_manager):
        print("[SERVER] Initializing global model...", flush=True)
        net = Net()
        ndarrays = [val.cpu().numpy() for _, val in net.state_dict().items()]
        params = ndarrays_to_parameters(ndarrays)
        self.previous_parameters = params
        self.previous_parameters_no_history = params  # Initialize for no history experiment
        return params

    def configure_fit(self, server_round, parameters, client_manager):
        # Wait until desired number of clients are connected
        clients = list(client_manager.all().values())
        print_start_load(server_round= server_round, desired_clients= self.cfg.num_clients, clients_num= len(clients))
        while len(clients) < self.cfg.num_clients:
            time.sleep(1)
            clients = list(client_manager.all().values())
            print_loading(clients_num= len(clients), desired_clients= self.cfg.num_clients)

        config = {
            "round": server_round,
            "use_he": self.cfg.use_he,
            "enable_poisoning": self.cfg.enable_poisoning,
            "use_random_disconnection": self.cfg.use_random_disconnection,
            "disconnect_prob": self.cfg.disconnect_prob,
        }
        print_training(server_round=server_round, clients_num= len(clients), desired_clients= self.cfg.num_clients)

        if self.cfg.use_he and self.he is not None:
            # Send HE public key and partial-encryption config
            import pickle
            import base64

            public_key_bytes = pickle.dumps(self.he.public_key)
            public_key_str = base64.b64encode(public_key_bytes).decode("utf-8")
            config.update(
                {
                    "he_public_key": public_key_str,
                    "he_encrypt_ratio": self.cfg.he_encrypt_ratio,
                    "he_mask_seed": self.cfg.he_mask_seed,
                }
            )

        return [(c, FitIns(parameters, config)) for c in clients]

    def aggregate_fit(self, server_round, results, failures):
        if not results:
            print(f"[SERVER] Round {server_round}: no results, keep previous parameters.")
            return self.previous_parameters, {}

        # Collect basic info (pure extraction only)
        active_updates: List[Tuple[int, Parameters, int, dict]] = []

        for _, fit_res in results:
            cid = int(fit_res.metrics.get("cid", 0))
            num_examples = fit_res.num_examples
            metrics = fit_res.metrics

            if self.cfg.use_random_disconnection and metrics.get("disconnected", False):
                # Disconnected clients are only recorded via metrics; historical
                # updates are handled by the availability feature module.
                continue
            active_updates.append((cid, fit_res.parameters, num_examples, metrics))

        # print(f"\n=== Round {server_round} ===")
        # print(f"Active clients this round: {len(active_updates)} / {self.cfg.num_clients}")

        # Record isolated accuracies and active rounds
        for cid, _, _, metrics in active_updates:
            iso = metrics.get("isolated_accuracy", 0.0)
            self.history["client_isolated_acc"].setdefault(cid, []).append(float(iso))
            self.history["client_active_rounds"].setdefault(cid, []).append(server_round)

        # Dispatch aggregation path to feature modules
        if self.cfg.use_he and self.he is not None:
            if self.cfg.use_defense or self.cfg.use_history_updates:
                print(
                    "[SERVER] WARNING: HE mode is enabled; defense/history switches are "
                    "currently ignored in this unified implementation."
                )
            try:
                from .features.privacy import aggregate_round_he
                aggregated = aggregate_round_he(
                    self.cfg,
                    server_round,
                    active_updates,
                    self.he,
                    self.history,
                    self.previous_parameters,
                )
            except ImportError as e:
                print(f"[WARNING] Could not import privacy module: {e}. Falling back to plain aggregation.")
                aggregated = self._aggregate_plain_with_optional_defense_and_history(
                    server_round, active_updates
                )
        else:
            # Run experiment with history updates
            aggregated = self._aggregate_plain_with_optional_defense_and_history(
                server_round, active_updates
            )
            
            # If we need to run both experiments, also run without history updates
            if self.run_both_experiments:
                # Temporarily disable history updates for this experiment
                original_use_history = self.cfg.use_history_updates
                self.cfg.use_history_updates = False
                
                # Run aggregation without history updates
                aggregated_no_history = self._aggregate_plain_with_optional_defense_and_history(
                    server_round, active_updates
                )
                
                # Restore original setting
                self.cfg.use_history_updates = original_use_history
                
                # Update the no history parameters
                self.previous_parameters_no_history = aggregated_no_history

        self.previous_parameters = aggregated
        return aggregated, {}

    def configure_evaluate(self, *args, **kwargs):
        return []

    def aggregate_evaluate(self, *args, **kwargs):
        return None, {}

    def evaluate(self, server_round, parameters):
        if self.evaluate_fn is None:
            return None
        
        # Evaluate model with history updates
        ndarrays = parameters_to_ndarrays(parameters)
        loss, metrics = self.evaluate_fn(server_round, ndarrays, {})
        real_global_acc = metrics['accuracy']
        
        # Evaluate model without history updates if running both experiments
        real_global_acc_no_history = None
        if self.run_both_experiments and self.previous_parameters_no_history is not None:
            ndarrays_no_history = parameters_to_ndarrays(self.previous_parameters_no_history)
            loss_no_history, metrics_no_history = self.evaluate_fn(server_round, ndarrays_no_history, {})
            real_global_acc_no_history = metrics_no_history['accuracy']
            print(f"--- Round {server_round} Analysis (no history) ---", flush=True)
            print(f"[ANALYSIS] >>> Global model accuracy (no history): {real_global_acc_no_history:.4f}", flush=True)
            print(f"[ANALYSIS] >>> Global model loss (no history): {loss_no_history:.4f}", flush=True)
        
        self.history["rounds"].append(server_round)
        self.history["global_acc"].append(real_global_acc)
        if real_global_acc_no_history is not None:
            self.history["global_acc_no_history"].append(real_global_acc_no_history)
        self.history["total_time"].append(get_timestamp_seconds() - self.previous_time)
        
        print_evalute(server_round=server_round, metrics=metrics, loss=loss)
        self.send_data()
        return loss,metrics

    def _aggregate_plain_with_optional_defense_and_history(
        self,   
        server_round: int,
        active_updates: List[Tuple[int, Parameters, int, dict]],
    ):
        """Plain aggregation with optional MAD+reputation defense and historical updates."""
        if not active_updates and not self.cfg.use_history_updates:
            print("[SERVER] No active updates and history disabled; keeping previous parameters.")
            # Return the appropriate previous parameters based on whether history is enabled
            if self.cfg.use_history_updates:
                return self.previous_parameters
            else:
                return self.previous_parameters_no_history if self.previous_parameters_no_history is not None else self.previous_parameters

        # --- Build list of available updates via availability feature module ---
        weights_results, stale_count = build_weight_results_with_history(
            self.cfg,
            server_round,
            active_updates,
            self.client_latest_updates,
        )
        if not weights_results:
            print("[SERVER] No usable updates; keeping previous parameters.")
            # Return the appropriate previous parameters based on whether history is enabled
            if self.cfg.use_history_updates:
                return self.previous_parameters
            else:
                return self.previous_parameters_no_history if self.previous_parameters_no_history is not None else self.previous_parameters

        # --- Aggregate either with standard FedAvg or MAD+reputation defense ---
        cids = [cid for cid, _, _, _ in weights_results]
        all_weights = [nds for _, nds, _, _ in weights_results]
        num_examples_array = np.array([w for _, _, w, _ in weights_results], dtype=np.float64)
        num_layers = len(all_weights[0])
        aggregated_weights: List[np.ndarray] = []

        if not self.cfg.use_defense:
            print(f"--- Round {server_round} Aggregation: Standard ---", flush= True)
            total_examples = float(num_examples_array.sum())
            weights_normalized = num_examples_array / max(total_examples, 1e-8)
            for layer_idx in range(num_layers):
                layer_weights = [weights[layer_idx] for weights in all_weights]
                layer_stack = np.stack(layer_weights, axis=0)
                avg_layer = np.mean(layer_stack, axis=0)
                aggregated_weights.append(avg_layer)
        else:
            print(f"--- Round {server_round} Aggregation: MAD + Reputation Defense ---", flush= True)
            aggregated_weights = aggregate_with_mad_reputation(
                self.cfg,
                weights_results,
                self.client_trusts,
                self.client_trust_history,
            )

        aggregated_params = ndarrays_to_parameters(aggregated_weights)

        # Track simple global accuracy proxy based on client-reported FL accuracies
        # fl_accs = [m.get("fl_accuracy", 0.0) for _, _, _, m in active_updates]
        # if fl_accs:
        #     global_acc = float(sum(fl_accs) / len(fl_accs))
        #     self.history["rounds"].append(server_round)
        #     self.history["global_acc"].append(global_acc)
        #     print(f"   >>> [Global Model] (proxy) Accuracy: {global_acc:.4f} <<<")

        return aggregated_params


def main():
    parser = build_arg_parser()
    args = parser.parse_args()
    cfg = config_from_args(args)

    # Set random seed for reproducibility
    import random
    random.seed(42)
    np.random.seed(42)
    torch.manual_seed(42)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(42)
        torch.cuda.manual_seed_all(42)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

    print("=== Unified FL Server Configuration ===", flush=True)
    print(cfg, flush=True)
    print(f"[cmd][cfg] {json.dumps(flconfig_to_dict(cfg=cfg))}", flush=True)

    evaluate_fn = get_evaluate_fn()

    strategy = UnifiedServerStrategy(cfg, evaluate_fn=evaluate_fn)

    fl.server.start_server(
        server_address=cfg.server_address,
        config=fl.server.ServerConfig(num_rounds=cfg.num_rounds),
        strategy=strategy,
    )
    # plot_all_results(
    #     strategy.history,
    #     strategy.cfg.use_he,
    #     strategy.cfg.use_random_disconnection or strategy.cfg.use_history_updates,
    #     strategy.cfg.use_defense
    # )
    plot_all_results(
        history=strategy.history,
        use_he=strategy.cfg.use_he,
        use_availability=(strategy.cfg.use_random_disconnection or strategy.cfg.use_history_updates),
        use_defense=strategy.cfg.use_defense,
        enable_poisoning=strategy.cfg.enable_poisoning
    )


if __name__ == "__main__":
    main()
