import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Subset
from torchvision.datasets import MNIST
from torchvision.transforms import Compose, ToTensor, Normalize
import matplotlib.pyplot as plt
import os
# This file was generated by team member Jiale Qin(20616174)
# Some function in this file was written by team member Mingyang Xue(20617494) Sirui Li(20617511)
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


class Net(nn.Module):
    """Simple CNN used as the common FL model."""

    def __init__(self) -> None:
        super().__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 4 * 4, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 4 * 4)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)


def train(net: nn.Module, trainloader: DataLoader, epochs: int = 1) -> None:
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(net.parameters(), lr=0.01, momentum=0.9)
    net.train()
    for _ in range(epochs):
        for images, labels in trainloader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            loss = criterion(net(images), labels)
            loss.backward()
            optimizer.step()


def test(net: nn.Module, testloader: DataLoader):
    criterion = nn.CrossEntropyLoss()
    correct, total, loss = 0, 0, 0.0
    net.eval()
    with torch.no_grad():
        for images, labels in testloader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs = net(images)
            loss += criterion(outputs, labels).item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    if len(testloader.dataset) == 0:
        return 0.0, 0.0
    return loss / len(testloader), correct / total


def load_data(cid: int, num_clients: int):
    """Non-IID split of MNIST.

    For 3 clients we follow the 0-3 / 4-6 / 7-9 split.
    For 8 clients we follow an overlapping label window similar to Robustness_poison_new.
    """
    
    data_dir = "./back_end/All3Feature/data"  # default
    tr = Compose([ToTensor(), Normalize((0.1307,), (0.3081,))])
    trainset = MNIST(data_dir, train=True, download=True, transform=tr)
    testset = MNIST(data_dir, train=False, download=True, transform=tr)

    cid = int(cid)

    if num_clients == 3:
        if cid == 1:
            labels_to_keep = [0, 1, 2, 3]
        elif cid == 2:
            labels_to_keep = [4, 5, 6]
        else:
            labels_to_keep = [7, 8, 9]
    else:
        label_map = {
            1: [0, 1, 2, 3],
            2: [1, 2, 3, 4],
            3: [2, 3, 4, 5],
            4: [3, 4, 5, 6],
            5: [5, 6, 7, 8],
            6: [6, 7, 8, 9],
            7: [7, 8, 9, 0],
            8: [8, 9, 0, 1],
        }
        labels_to_keep = label_map.get(cid, list(range(10)))

    indices = [i for i, label in enumerate(trainset.targets) if label in labels_to_keep]
    train_subset = Subset(trainset, indices)

    return DataLoader(train_subset, batch_size=32, shuffle=True), DataLoader(
        testset, batch_size=32
    )

def poison_dataset(subset: Subset, source_label: int, target_label: int) -> None:
    """Simple label-flipping attack on a subset view of MNIST."""
    all_targets = subset.dataset.targets.clone()
    subset_indices = subset.indices
    subset_indices_tensor = torch.tensor(subset_indices)
    mask = all_targets[subset_indices_tensor] == source_label
    indices_to_poison = subset_indices_tensor[mask]
    all_targets[indices_to_poison] = target_label
    subset.dataset.targets = all_targets

# New Method

def load_data_new(label_list: list, num_clients: int):    
    data_dir = "./back_end/All3Feature/data"  # default
    tr = Compose([ToTensor(), Normalize((0.1307,), (0.3081,))])
    trainset = MNIST(data_dir, train=True, download=True, transform=tr)
    testset = MNIST(data_dir, train=False, download=True, transform=tr)

    labels_to_keep = [i for i, keep in enumerate(label_list) if keep == 1]

    indices = [i for i, label in enumerate(trainset.targets) if label in labels_to_keep]
    train_subset = Subset(trainset, indices)

    return DataLoader(train_subset, batch_size=32, shuffle=True), DataLoader(
        testset, batch_size=32
    )

def get_label(cid: int, num_clients: int):
    # Get the list of active labels first
    if num_clients == 3:
        if cid == 1:
            active_labels = [0, 1, 2, 3]
        elif cid == 2:
            active_labels = [4, 5, 6]
        else:  # cid == 3
            active_labels = [7, 8, 9]
    else:
        label_map = {
            1: [0, 1, 2, 3],
            2: [1, 2, 3, 4],
            3: [2, 3, 4, 5],
            4: [3, 4, 5, 6],
            5: [5, 6, 7, 8],
            6: [6, 7, 8, 9],
            7: [7, 8, 9, 0],
            8: [8, 9, 0, 1],
        }
        active_labels = label_map.get(cid, list(range(10)))
    
    # Convert to binary mask [0,1,0,1,...]
    label_mask = [0] * 10
    for label in active_labels:
        label_mask[label] = 1
    
    return label_mask

def display_samples_by_label(save_dir="static\image_folder\label_samples"):
    """Save sample images for each label into separate files."""
    os.makedirs(save_dir, exist_ok=True)
    
    data_dir = "./back_end/All3Feature/data"  # default
    tr = Compose([ToTensor(), Normalize((0.1307,), (0.3081,))])
    dataset = MNIST(data_dir, train=True, download=True, transform=tr)
    
    # Group images by label
    label_images = {}
    for i in range(min(len(dataset), 1000)):  # Limit to first 1000 images
        img, label = dataset[i]
        if label not in label_images:
            label_images[label] = []
        if len(label_images[label]) < 1:  # Save 5 images per label
            label_images[label].append(img)
    
    # Create a figure for each label
    for label, images in label_images.items():
        fig, axes = plt.subplots(1, len(images), figsize=(len(images)*2, 2))
        if len(images) == 1:
            axes = [axes]
        
        for i, img in enumerate(images):
            axes[i].imshow(img.squeeze(), cmap='gray')
            axes[i].set_title(f"Label: {label}")
            axes[i].axis('off')
        
        plt.tight_layout()
        save_path = os.path.join(save_dir, f"label_{label}.png")
        plt.savefig(save_path)
        plt.close(fig)

def main():
    display_samples_by_label()

if __name__ == "__main__":
    main()
