import numpy as np
from phe import paillier
import pickle
import base64
# This file was generated by team member Jiale Qin(20616174)
DEFAULT_ENCRYPT_RATIO = 0.02
DEFAULT_MASK_SEED = 42


def generate_encryption_masks(parameters_list, encrypt_ratio=DEFAULT_ENCRYPT_RATIO, seed=DEFAULT_MASK_SEED):
    masks = []
    for layer_idx, param in enumerate(parameters_list):
        size = param.size
        rng = np.random.RandomState(seed + layer_idx)
        mask = rng.rand(size) < encrypt_ratio
        masks.append(mask.reshape(param.shape))
    return masks


class PaillierHE:

    def __init__(self, public_key=None, private_key=None, key_size=2048):
        if public_key is None and private_key is None:
            self.public_key, self.private_key = paillier.generate_paillier_keypair(n_length=key_size)
        else:
            self.public_key = public_key
            self.private_key = private_key
    
    def get_public_key(self):
        return self.public_key
    
    def quantize(self, float_array, scale=10**6):
        return (float_array * scale).astype(np.int64)
    
    def dequantize(self, int_array, scale=10**6):
        return int_array.astype(np.float64) / scale
    
    def encrypt_element(self, value, scale=10**6):
        quantized = int(np.int64(np.round(value * scale)))
        return self.public_key.encrypt(quantized)
    
    def decrypt_element(self, enc_value, scale=10**6):
        return self.private_key.decrypt(enc_value) / scale
    
    def encrypt_array(self, array, scale=10**6):
        quantized = self.quantize(array, scale)
        encrypted = []
        for value in quantized.flatten():
            encrypted.append(self.public_key.encrypt(int(np.int64(value))))
        encrypted_array = np.array(encrypted).reshape(array.shape)
        return encrypted_array
    
    def decrypt_array(self, encrypted_array, scale=10**6):
        decrypted = []
        for enc_value in encrypted_array.flatten():
            decrypted.append(self.private_key.decrypt(enc_value))
        decrypted_array = np.array(decrypted, dtype=np.int64).reshape(encrypted_array.shape)
        return self.dequantize(decrypted_array, scale)
    
    def encrypt_parameters_partial(self, parameters_list, masks, scale=10**6):
        result = []
        for param, mask in zip(parameters_list, masks):
            layer = np.empty(param.shape, dtype=object)
            flat_param = param.flatten()
            flat_mask = mask.flatten()
            for i in range(param.size):
                if flat_mask[i]:
                    layer.flat[i] = self.encrypt_element(flat_param[i], scale)
                else:
                    layer.flat[i] = flat_param[i].astype(np.float64)
            result.append(layer)
        return result
    
    def decrypt_parameters_partial(self, mixed_params_list, masks, scale=10**6):
        result = []
        for mixed_layer, mask in zip(mixed_params_list, masks):
            layer = np.zeros(mixed_layer.shape, dtype=np.float64)
            flat_mask = mask.flatten()
            for i in range(mixed_layer.size):
                val = mixed_layer.flat[i]
                if flat_mask[i]:
                    layer.flat[i] = self.decrypt_element(val, scale)
                else:
                    layer.flat[i] = float(val)
            result.append(layer)
        return result


def serialize_partial_encrypted_parameters(mixed_params_list, masks):
    serialized = []
    for mixed_layer, mask in zip(mixed_params_list, masks):
        flat_layer = mixed_layer.flatten()
        flat_mask = mask.flatten()
        encrypted_indices = np.where(flat_mask)[0].tolist()
        plaintext_indices = np.where(~flat_mask)[0].tolist()
        
        encrypted_data = []
        for idx in encrypted_indices:
            enc_bytes = pickle.dumps(flat_layer[idx])
            encrypted_data.append(base64.b64encode(enc_bytes).decode('utf-8'))
        
        plaintext_values = np.array([float(flat_layer[i]) for i in plaintext_indices], dtype=np.float64)
        plaintext_bytes = pickle.dumps(plaintext_values)
        plaintext_str = base64.b64encode(plaintext_bytes).decode('utf-8')
        
        serialized.append({
            'shape': mixed_layer.shape,
            'encrypted_indices': encrypted_indices,
            'encrypted_data': encrypted_data,
            'plaintext_indices': plaintext_indices,
            'plaintext_data': plaintext_str,
        })
    return serialized


def deserialize_partial_encrypted_parameters(serialized_params_list, masks):
    result = []
    for serialized, mask in zip(serialized_params_list, masks):
        shape = serialized['shape']
        size = int(np.prod(shape))
        layer = np.empty(shape, dtype=object)

        plaintext_bytes = base64.b64decode(serialized['plaintext_data'].encode('utf-8'))
        plaintext_values = pickle.loads(plaintext_bytes)
        for i, idx in enumerate(serialized['plaintext_indices']):
            layer.flat[idx] = plaintext_values[i]

        for i, idx in enumerate(serialized['encrypted_indices']):
            enc_bytes = base64.b64decode(serialized['encrypted_data'][i].encode('utf-8'))
            layer.flat[idx] = pickle.loads(enc_bytes)
        
        result.append(layer)
    return result


def secure_aggregate_partial_encrypted(encrypted_params_list, num_examples_list, public_key, masks):
    if not encrypted_params_list:
        return None
    
    num_layers = len(encrypted_params_list[0])
    aggregated_result = []

    for layer_idx in range(num_layers):
        layer_shape = encrypted_params_list[0][layer_idx].shape
        mask = masks[layer_idx]
        flat_mask = mask.flatten()

        aggregated_layer = np.empty(layer_shape, dtype=object)
        zero_encrypted = public_key.encrypt(0)
        
        for i in range(int(np.prod(layer_shape))):
            if flat_mask[i]:
                aggregated_layer.flat[i] = zero_encrypted
            else:
                aggregated_layer.flat[i] = 0.0

        for client_params, num_examples in zip(encrypted_params_list, num_examples_list):
            client_layer = client_params[layer_idx]
            for i in range(client_layer.size):
                if flat_mask[i]:
                    weighted = client_layer.flat[i] * num_examples
                    aggregated_layer.flat[i] = aggregated_layer.flat[i] + weighted
                else:
                    aggregated_layer.flat[i] = aggregated_layer.flat[i] + float(client_layer.flat[i]) * num_examples
        
        aggregated_result.append(aggregated_layer)
    
    return aggregated_result


def init_he_from_config(config, client_id=None):
    use_he = config.get("use_he", False)
    he = None
    
    if use_he and "he_public_key" in config:
        public_key_bytes = base64.b64decode(config["he_public_key"].encode('utf-8'))
        public_key = pickle.loads(public_key_bytes)
        he = PaillierHE(public_key=public_key)
        if client_id is not None:
            print(f"[Client {client_id}] HE initialized with public key from server")
        else:
            print("[Client] HE initialized with public key from server")
    
    return he, use_he


def encrypt_and_return_params(updated_params, he, use_he, client_id=None, num_examples=0, metrics=None, config=None):
    if use_he and he is not None:
        encrypt_ratio = (config or {}).get("he_encrypt_ratio", DEFAULT_ENCRYPT_RATIO)
        mask_seed = (config or {}).get("he_mask_seed", DEFAULT_MASK_SEED)
        if client_id is not None:
            print(f"[Client {client_id}] Encrypting parameters with HE (partial, ratio={encrypt_ratio})...")
        else:
            print("[Client] Encrypting parameters with HE (partial)...")
        
        masks = generate_encryption_masks(updated_params, encrypt_ratio=encrypt_ratio, seed=mask_seed)
        mixed_params = he.encrypt_parameters_partial(updated_params, masks)
        serialized_params = serialize_partial_encrypted_parameters(mixed_params, masks)

        flower_compatible_params = []
        for serialized_param in serialized_params:
            param_bytes = pickle.dumps(serialized_param)
            param_array = np.frombuffer(param_bytes, dtype=np.uint8)
            flower_compatible_params.append(param_array)
        
        return (
            flower_compatible_params,
            num_examples,
            metrics or {}
        )
    else:
        return (
            updated_params,
            num_examples,
            metrics or {}
        )
