import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Subset
from torchvision.datasets import MNIST
from torchvision.transforms import Compose, ToTensor, Normalize
# This file was generated by team member Jiale Qin(20616174)
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*4*4,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)

    def forward(self,x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1,16*4*4)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)


def train(net, trainloader, epochs):
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(net.parameters(), lr=0.01, momentum=0.9)
    net.train()
    for _ in range(epochs):
        for images, labels in trainloader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            loss = criterion(net(images), labels)
            loss.backward()
            optimizer.step()


def train_attack_mode(net, trainloader, lr=0.01):
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(net.parameters(), lr=lr, momentum=0)
    net.train()
    batch = next(iter(trainloader))
    images, labels = batch[0].to(DEVICE), batch[1].to(DEVICE)
    optimizer.zero_grad()
    loss = criterion(net(images), labels)
    loss.backward()
    optimizer.step()


def compute_sgd_update_delta(model, x, y, lr=0.01, create_graph=False):
    criterion = nn.CrossEntropyLoss()
    loss = criterion(model(x), y)
    grads = torch.autograd.grad(loss, list(model.parameters()), create_graph=create_graph)
    return [-lr * g for g in grads]


def verify_update_consistency():
    from torch.utils.data import DataLoader, Subset
    trainloader, _ = load_data_digit0()
    subset_one = Subset(trainloader.dataset, [0])
    attack_loader = DataLoader(subset_one, batch_size=1, shuffle=False)
    x, y = next(iter(attack_loader))
    x, y = x.to(DEVICE), y.to(DEVICE)

    net1 = Net().to(DEVICE)
    net2 = Net().to(DEVICE)
    net2.load_state_dict(net1.state_dict(), strict=True)

    train_attack_mode(net1, attack_loader, lr=0.01)
    delta_train = [p.detach().clone() - net2.state_dict()[k].detach().clone()
                  for (k, p) in net1.state_dict().items()]

    net2.train()
    delta_compute = compute_sgd_update_delta(net2, x, y, lr=0.01, create_graph=False)
    delta_compute_sd = [p.cpu() for p in delta_compute]
    delta_train_sd = [p.cpu() for p in delta_train]

    max_diff = max((a - b).abs().max().item() for a, b in zip(delta_train_sd, delta_compute_sd))
    print(f"[verify] max |delta_train - delta_compute| = {max_diff:.2e}")
    assert max_diff < 1e-5, "train_attack_mode  compute_sgd_update_delta"
    print("[verify] OK")


def test(net, testloader):
    criterion = nn.CrossEntropyLoss()
    correct, total, loss = 0, 0, 0.0
    net.eval()
    with torch.no_grad():
        for images, labels in testloader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs = net(images)
            loss += criterion(outputs, labels).item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    if len(testloader.dataset) == 0: return 0.0, 0.0
    return loss / len(testloader), correct / total


def load_data(cid):
    tr = Compose([ToTensor(), Normalize((0.1307,), (0.3081,))])
    trainset = MNIST("./data", train=True, download=True, transform=tr)
    testset = MNIST("./data", train=False, download=True, transform=tr)

    cid = int(cid)
    if cid == 1:
        labels_to_keep = [0, 1, 2, 3]
    elif cid == 2:
        labels_to_keep = [4, 5, 6]
    else:
        labels_to_keep = [7, 8, 9]

    indices = [i for i, label in enumerate(trainset.targets) if label in labels_to_keep]
    train_subset = Subset(trainset, indices)

    return DataLoader(train_subset, batch_size=32, shuffle=True), DataLoader(testset, batch_size=32)


def load_data_digit0():
    tr = Compose([ToTensor(), Normalize((0.1307,), (0.3081,))])
    trainset = MNIST("./data", train=True, download=True, transform=tr)
    testset = MNIST("./data", train=False, download=True, transform=tr)
    train_indices = [i for i, label in enumerate(trainset.targets) if label == 0]
    test_indices = [i for i, label in enumerate(testset.targets) if label == 0]
    train_subset = Subset(trainset, train_indices)
    test_subset = Subset(testset, test_indices)
    return (
        DataLoader(train_subset, batch_size=32, shuffle=True),
        DataLoader(test_subset, batch_size=32),
    )

