import torch
import numpy as np
from pathlib import Path

from utils.model_utils import Net, compute_sgd_update_delta
# This file was generated by team member Jiale Qin(20616174)
MNIST_MEAN, MNIST_STD = 0.1307, 0.3081


def load_npz(path):
    d = np.load(path)
    keys = sorted([f for f in d.files if f.startswith("p")], key=lambda x: int(x[1:]))
    return [d[k] for k in keys]


def flat_torch(params):
    return torch.cat([p.reshape(-1) for p in params])


def total_variation(x):
    tv_h = torch.mean(torch.abs(x[:, :, 1:, :] - x[:, :, :-1, :]))
    tv_w = torch.mean(torch.abs(x[:, :, :, 1:] - x[:, :, :, :-1]))
    return tv_h + tv_w


def set_model_from_ndarrays(model, nds):
    sd = model.state_dict()
    new_sd = {}
    for (k, v), arr in zip(sd.items(), nds):
        new_sd[k] = torch.tensor(arr, dtype=v.dtype, device=v.device)
    model.load_state_dict(new_sd, strict=True)


def _normalize_x(x_raw):
    return (x_raw - MNIST_MEAN) / MNIST_STD


def compute_delta_with_model(model, x_raw, y, lr=0.01, device="cpu", create_graph=False):
    model.train()
    x_norm = _normalize_x(x_raw)
    return compute_sgd_update_delta(model, x_norm, y, lr=lr, create_graph=create_graph)


def simulate_one_step_update(theta_model, x_raw, y, lr=0.01, device="cpu", create_graph=False):
    model = Net().to(device)
    model.load_state_dict(theta_model.state_dict(), strict=True)
    return compute_delta_with_model(model, x_raw, y, lr=lr, device=device, create_graph=create_graph)


def run_attack(
    theta, delta_obs_list, device, iters=12000, lr_img=0.15, lr_sgd=0.01,
    tv_alpha=4e-5, use_fc3_only=False, l2_weight=1.0, x_init=None,
    lr_decay_steps=4000, lr_decay_gamma=0.5, lbfgs_refine_steps=0,
    model=None,
):
    if model is None:
        model = Net().to(device)
    model.load_state_dict(theta.state_dict(), strict=True)

    if use_fc3_only:
        delta_obs = delta_obs_list[8:10]
    else:
        delta_obs = delta_obs_list
    delta_obs_flat = flat_torch(delta_obs)
    delta_obs_norm = delta_obs_flat / (delta_obs_flat.norm() + 1e-12)

    y = torch.tensor([0], device=device, dtype=torch.long)
    if x_init is not None:
        x = x_init.clone().detach().requires_grad_(True)
    else:
        x = (torch.rand(1, 1, 28, 28, device=device) * 0.12 + 0.44).detach().requires_grad_(True)

    opt = torch.optim.Adam([x], lr=lr_img)
    best_loss, best_x = float("inf"), None

    print_every = max(1000, iters // 5)

    for t in range(iters):
        if lr_decay_steps and (t + 1) % lr_decay_steps == 0 and t > 0:
            for g in opt.param_groups:
                g["lr"] *= lr_decay_gamma

        opt.zero_grad()
        delta_pred = compute_delta_with_model(model, x, y, lr=lr_sgd, device=device, create_graph=True)
        if use_fc3_only:
            delta_pred = delta_pred[8:10]
        delta_pred_flat = flat_torch(delta_pred)
        delta_pred_norm = delta_pred_flat / (delta_pred_flat.norm() + 1e-12)

        loss_cos = 1.0 - torch.sum(delta_pred_norm * delta_obs_norm)
        loss_l2 = torch.sum((delta_pred_flat - delta_obs_flat) ** 2) / (delta_obs_flat.norm() ** 2 + 1e-8)
        loss_tv = tv_alpha * total_variation(x)
        loss = loss_cos + l2_weight * loss_l2 + loss_tv

        loss.backward()
        opt.step()
        with torch.no_grad():
            x.clamp_(0.0, 1.0)

        if loss.item() < best_loss:
            best_loss = loss.item()
            best_x = x.detach().clone()
        if (t + 1) % print_every == 0:
            print(f"  iter {t+1} loss={best_loss:.4f} cos={loss_cos.item():.4f} l2={loss_l2.item():.4f}")

    if best_x is not None and lbfgs_refine_steps > 0:
        x = best_x.detach().clone().requires_grad_(True)
        opt_lbfgs = torch.optim.LBFGS([x], lr=1.0, max_iter=20, history_size=10)

        def closure():
            opt_lbfgs.zero_grad()
            delta_pred = compute_delta_with_model(model, x, y, lr=lr_sgd, device=device, create_graph=True)
            if use_fc3_only:
                delta_pred = delta_pred[8:10]
            delta_pred_flat = flat_torch(delta_pred)
            delta_pred_norm = delta_pred_flat / (delta_pred_flat.norm() + 1e-12)
            loss_cos = 1.0 - torch.sum(delta_pred_norm * delta_obs_norm)
            loss_l2 = torch.sum((delta_pred_flat - delta_obs_flat) ** 2) / (delta_obs_flat.norm() ** 2 + 1e-8)
            loss_tv = tv_alpha * total_variation(x)
            loss = loss_cos + l2_weight * loss_l2 + loss_tv
            loss.backward()
            return loss

        for _ in range(lbfgs_refine_steps):
            opt_lbfgs.step(closure)
            with torch.no_grad():
                x.clamp_(0.0, 1.0)
        best_x = x.detach().clone()

    return best_x


def main(
    log_dir="eavesdrop_logs_x",
    round_id=1,
    cid=1,
    iters=12000,
    restarts=5,
    lr_img=0.15,
    lr_sgd=0.01,
    tv_alpha=4e-5,
    use_fc3_only=False,
    l2_weight=1.0,
    lbfgs_refine_steps=5,
):
    log_dir = Path(log_dir)
    global_path = log_dir / f"r{round_id}_cid{cid}_global.npz"
    upload_path = log_dir / f"r{round_id}_cid{cid}_upload.npz"

    if not global_path.exists() or not upload_path.exists():
        print(f"[error] miss document: {global_path} or {upload_path}")
        return

    global_nd = load_npz(global_path)
    upload_nd = load_npz(upload_path)

    meta_path = log_dir / f"r{round_id}_cid{cid}_meta.json"
    lr_sgd = 0.01
    use_he = False
    if meta_path.exists():
        import json
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        lr_sgd = float(meta.get("attack_lr", lr_sgd))
        use_he = bool(meta.get("use_he", False))

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    he_encrypted = upload_nd[0].dtype == np.uint8
    if he_encrypted:
        use_he = True
        delta_obs_list = [
            torch.zeros(g.shape, dtype=torch.float32, device=device)
            for g in global_nd
        ]
    else:
        delta_obs_list = [
            torch.tensor(u.astype(np.float32) - g.astype(np.float32), dtype=torch.float32, device=device)
            for u, g in zip(upload_nd, global_nd)
        ]
    print(f"[info] use lr_sgd={lr_sgd}")
    delta_norm = torch.cat([p.reshape(-1) for p in delta_obs_list]).norm().item()
    print(f"[info] Input Difference Norm={delta_norm:.6f}" + (" [encrypted-input]" if he_encrypted else ""))

    theta = Net().to(device)
    set_model_from_ndarrays(theta, global_nd)
    theta.eval()

    shared_model = Net().to(device)
    best_recon = None
    best_loss = float("inf")
    y_zero = torch.tensor([0], device=device, dtype=torch.long)
    for r in range(restarts):
        print(f"[info] restart {r+1}/{restarts}")
        x_recon = run_attack(
            theta, delta_obs_list, device,
            iters=iters, lr_img=lr_img, lr_sgd=lr_sgd, tv_alpha=tv_alpha,
            use_fc3_only=use_fc3_only, l2_weight=l2_weight,
            lbfgs_refine_steps=lbfgs_refine_steps,
            model=shared_model,
        )
        shared_model.load_state_dict(theta.state_dict(), strict=True)
        delta_pred = compute_delta_with_model(shared_model, x_recon, y_zero, lr=lr_sgd, device=device, create_graph=False)
        if use_fc3_only:
            delta_pred = delta_pred[8:10]
        delta_obs_sub = delta_obs_list[8:10] if use_fc3_only else delta_obs_list
        dp = flat_torch(delta_pred)
        do = flat_torch(delta_obs_sub)
        cos = (dp @ do) / (dp.norm() * do.norm() + 1e-12)
        loss = 1 - cos.item()
        if loss < best_loss:
            best_loss = loss
            best_recon = x_recon

    out = best_recon.cpu().numpy()
    recon_suffix = "_he" if use_he else ""
    recon_npy = log_dir / f"r{round_id}_cid{cid}_recon{recon_suffix}.npy"
    recon_png = log_dir / f"r{round_id}_cid{cid}_recon{recon_suffix}.png"
    np.save(recon_npy, out)
    try:
        import matplotlib.pyplot as plt
        plt.imsave(recon_png, out[0, 0], cmap="gray", vmin=0, vmax=1)
        print(f"[info] image saved: {recon_png} (score={best_loss:.4f})")
    except ImportError:
        pass


def verify_ground_truth(log_dir="eavesdrop_logs_x", round_id=1, cid=1):
    from torch.utils.data import DataLoader, Subset
    from utils.model_utils import load_data_digit0
    import json

    log_dir = Path(log_dir)
    global_nd = load_npz(log_dir / f"r{round_id}_cid{cid}_global.npz")
    upload_nd = load_npz(log_dir / f"r{round_id}_cid{cid}_upload.npz")
    meta_path = log_dir / f"r{round_id}_cid{cid}_meta.json"
    lr_sgd = 0.01
    meta = {}
    if meta_path.exists():
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        lr_sgd = float(meta.get("attack_lr", lr_sgd))

    if meta.get("num_examples", 0) != 1:
        print(f"[warn] num_examples={meta.get('num_examples')} != 1，")


    trainloader, _ = load_data_digit0()
    subset_one = Subset(trainloader.dataset, [0])
    attack_loader = DataLoader(subset_one, batch_size=1, shuffle=False)
    img_norm, label = next(iter(attack_loader))
    x_raw = img_norm * MNIST_STD + MNIST_MEAN
    x_raw = x_raw.detach()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    theta = Net().to(device)
    set_model_from_ndarrays(theta, global_nd)
    theta.eval()

    delta_obs_list = [
        torch.tensor(u.astype(np.float32) - g.astype(np.float32), dtype=torch.float32, device=device)
        for u, g in zip(upload_nd, global_nd)
    ]
    delta_pred = simulate_one_step_update(theta, x_raw.to(device), label.to(device), lr=lr_sgd, device=device, create_graph=False)

    cos_full = (flat_torch(delta_pred) @ flat_torch(delta_obs_list)) / (flat_torch(delta_pred).norm() * flat_torch(delta_obs_list).norm() + 1e-12)
    cos_fc3 = (flat_torch(delta_pred[8:10]) @ flat_torch(delta_obs_list[8:10])) / (flat_torch(delta_pred[8:10]).norm() * flat_torch(delta_obs_list[8:10]).norm() + 1e-12)
    print(f"[verify] cos(full)={cos_full.item():.6f}, cos(fc3)={cos_fc3.item():.6f}")


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--log_dir", default="eavesdrop_logs_x")
    p.add_argument("--round", type=int, default=1)
    p.add_argument("--cid", type=int, default=1)
    p.add_argument("--iters", type=int, default=12000)
    p.add_argument("--restarts", type=int, default=5)
    p.add_argument("--fc3_only", action="store_true")
    p.add_argument("--verify", action="store_true")
    p.add_argument("--no_lbfgs", action="store_true")
    args = p.parse_args()

    if args.verify:
        verify_ground_truth(log_dir=args.log_dir, round_id=args.round, cid=args.cid)
    else:
        main(
            log_dir=args.log_dir,
            round_id=args.round,
            cid=args.cid,
            iters=args.iters,
            restarts=args.restarts,
            use_fc3_only=args.fc3_only,
            lbfgs_refine_steps=0 if args.no_lbfgs else 5,
        )
