import warnings
from pathlib import Path
from collections import OrderedDict

import flwr as fl
import torch
from torch.utils.data import DataLoader, Subset

from utils.model_utils import Net, train, train_attack_mode, test, load_data_digit0
from utils.he_utils import init_he_from_config, encrypt_and_return_params
# This file was generated by team member Xinchen Dai(20616310)
MNIST_MEAN, MNIST_STD = 0.1307, 0.3081
GROUND_TRUTH_DIR = "eavesdrop_logs_x"

warnings.filterwarnings("ignore")


class ClientX(fl.client.NumPyClient):
    def __init__(self):
        self.cid = 1
        self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        self.trainloader, self.testloader = load_data_digit0()
        self.net_fl = Net().to(self.device)
        self.he = None
        self.use_he = False
        n_train = len(self.trainloader.dataset)
        n_test = len(self.testloader.dataset)
        print(f"[clientx] Data loaded: train={n_train}, test={n_test} (all digit 0). ")

    def get_parameters(self, config):
        return [val.cpu().numpy() for _, val in self.net_fl.state_dict().items()]

    def set_parameters(self, net, parameters):
        params_dict = zip(net.state_dict().keys(), parameters)
        state_dict = OrderedDict({k: torch.tensor(v) for k, v in params_dict})
        net.load_state_dict(state_dict, strict=True)

    def fit(self, parameters, config):
        round_num = config.get("round", "Unknown")
        if self.he is None:
            self.he, self.use_he = init_he_from_config(config, client_id=self.cid)

        self.set_parameters(self.net_fl, parameters)
        loss_fl, acc_fl = test(self.net_fl, self.testloader)

        attack_mode = config.get("attack_mode", False)
        if attack_mode:
            subset_one = Subset(self.trainloader.dataset, [0])
            attack_loader = DataLoader(subset_one, batch_size=1, shuffle=False)
            img_norm, _ = next(iter(attack_loader))
            img_raw = (img_norm * MNIST_STD + MNIST_MEAN).clamp(0.0, 1.0)
            out_dir = Path(GROUND_TRUTH_DIR)
            out_dir.mkdir(parents=True, exist_ok=True)
            gt_path = out_dir / f"r{round_num}_cid{self.cid}_ground_truth.png"
            try:
                import matplotlib.pyplot as plt
                plt.imsave(gt_path, img_raw[0, 0].cpu().numpy(), cmap="gray", vmin=0, vmax=1)
                print(f"[clientx] saved: {gt_path}")
            except Exception as e:
                print(f"[clientx] : {e}")
            attack_loader = DataLoader(subset_one, batch_size=1, shuffle=False)
            attack_lr = config.get("attack_lr", 0.01)
            train_attack_mode(self.net_fl, attack_loader, lr=attack_lr)
            num_examples = 1
        else:
            train(self.net_fl, self.trainloader, epochs=1)
            num_examples = len(self.trainloader.dataset)

        updated_params = self.get_parameters(config={})
        print(f"[clientx] Round {round_num}: FL_Acc={acc_fl:.4f}")

        return encrypt_and_return_params(
            updated_params,
            self.he,
            self.use_he,
            client_id=self.cid,
            num_examples=num_examples,
            metrics={"cid": self.cid, "fl_accuracy": float(acc_fl)},
            config=config,
        )

    def evaluate(self, parameters, config):
        self.set_parameters(self.net_fl, parameters)
        loss, accuracy = test(self.net_fl, self.testloader)
        return float(loss), len(self.testloader.dataset), {"accuracy": float(accuracy)}


if __name__ == "__main__":
    print(" clientx starting (digit 0 only)")
    fl.client.start_client(
        server_address="127.0.0.1:8081",
        client=ClientX().to_client(),
    )
