import json
import pickle
import base64
import time
from pathlib import Path

import numpy as np
import flwr as fl
from flwr.common import ndarrays_to_parameters, parameters_to_ndarrays
from flwr.common import FitIns

from utils.model_utils import Net
from utils.he_utils import (
    PaillierHE,
    generate_encryption_masks,
    deserialize_partial_encrypted_parameters,
    secure_aggregate_partial_encrypted,
    DEFAULT_ENCRYPT_RATIO,
    DEFAULT_MASK_SEED,
)
# This file was generated by team member Xinchen Dai(20616310)
DESIRED_CLIENTS = 1
EAVESDROP_OUT_DIR = "eavesdrop_logs_x"
ATTACK_EVAL_MODE = True
ATTACK_LR = 0.01
USE_HE = False


def save_eavesdrop_packet(out_dir, server_round, cid, global_params_nd, raw_fit_parameters, meta: dict):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        out_dir / f"r{server_round}_cid{cid}_global.npz",
        **{f"p{i}": arr for i, arr in enumerate(global_params_nd)},
    )
    raw_nd = parameters_to_ndarrays(raw_fit_parameters)
    np.savez_compressed(
        out_dir / f"r{server_round}_cid{cid}_upload.npz",
        **{f"p{i}": arr for i, arr in enumerate(raw_nd)},
    )
    (out_dir / f"r{server_round}_cid{cid}_meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


class ServerXStrategy(fl.server.strategy.Strategy):
    def __init__(self, total_rounds, use_he=False):
        self.total_rounds = total_rounds
        self.use_he = use_he
        self.history = {"rounds": [], "global_acc": []}
        if self.use_he:
            print("[serverx] Initializing Paillier HE...")
            self.he = PaillierHE(key_size=1024)
            print("[serverx] HE keys generated")
        else:
            self.he = None

    def initialize_parameters(self, client_manager):
        print("[serverx] Initializing Global Model...")
        net = Net()
        ndarrays = [val.cpu().numpy() for _, val in net.state_dict().items()]
        return ndarrays_to_parameters(ndarrays)

    def configure_fit(self, server_round, parameters, client_manager):
        self.last_global_parameters = parameters
        clients = list(client_manager.all().values())
        while len(clients) < DESIRED_CLIENTS:
            time.sleep(1)
            clients = list(client_manager.all().values())
        config = {"round": server_round}
        if ATTACK_EVAL_MODE:
            config["attack_mode"] = True
            config["attack_batch_size"] = 1
            config["attack_steps"] = 1
            config["attack_lr"] = ATTACK_LR
        if self.use_he and server_round == 1:
            config["he_public_key"] = base64.b64encode(pickle.dumps(self.he.public_key)).decode("utf-8")
            config["he_encrypt_ratio"] = DEFAULT_ENCRYPT_RATIO
            config["he_mask_seed"] = DEFAULT_MASK_SEED
            config["use_he"] = True
        elif self.use_he:
            config["use_he"] = True
            config["he_encrypt_ratio"] = DEFAULT_ENCRYPT_RATIO
            config["he_mask_seed"] = DEFAULT_MASK_SEED
        return [(c, FitIns(parameters, config)) for c in clients]

    def aggregate_fit(self, server_round, results, failures):
        if not results:
            return None, {}

        global_params_nd = parameters_to_ndarrays(self.last_global_parameters)
        for _, fit_res in results:
            cid = fit_res.metrics.get("cid", 1)
            save_eavesdrop_packet(
                out_dir=EAVESDROP_OUT_DIR,
                server_round=server_round,
                cid=cid,
                global_params_nd=global_params_nd,
                raw_fit_parameters=fit_res.parameters,
                meta={
                    "round": server_round,
                    "cid": cid,
                    "num_examples": fit_res.num_examples,
                    "use_he": bool(self.use_he),
                    "he_encrypt_ratio": DEFAULT_ENCRYPT_RATIO,
                    "he_mask_seed": DEFAULT_MASK_SEED,
                    "attack_lr": ATTACK_LR,
                },
            )

        if self.use_he:
            param_bytes_list = parameters_to_ndarrays(results[0][1].parameters)
            serialized_params_0 = [pickle.loads(p.tobytes()) for p in param_bytes_list]
            shapes = [s["shape"] for s in serialized_params_0]
            dummy_params = [np.zeros(s, dtype=np.float64) for s in shapes]
            masks = generate_encryption_masks(
                dummy_params,
                encrypt_ratio=DEFAULT_ENCRYPT_RATIO,
                seed=DEFAULT_MASK_SEED,
            )
            encrypted_params_list = []
            num_examples_list = []
            for _, fit_res in results:
                param_bytes_list = parameters_to_ndarrays(fit_res.parameters)
                serialized_params = [pickle.loads(p.tobytes()) for p in param_bytes_list]
                encrypted_params = deserialize_partial_encrypted_parameters(serialized_params, masks)
                encrypted_params_list.append(encrypted_params)
                num_examples_list.append(fit_res.num_examples)
            aggregated_encrypted = secure_aggregate_partial_encrypted(
                encrypted_params_list,
                num_examples_list,
                self.he.public_key,
                masks,
            )
            aggregated_weights = self.he.decrypt_parameters_partial(aggregated_encrypted, masks)
            total_examples = sum(num_examples_list)
            aggregated_weights = [w / total_examples for w in aggregated_weights]
            parameters_aggregated = ndarrays_to_parameters(aggregated_weights)
        else:
            weights_results = [
                (parameters_to_ndarrays(fit_res.parameters), fit_res.num_examples)
                for _, fit_res in results
            ]
            total_examples = sum(n for _, n in weights_results)
            aggregated_weights = [
                np.zeros_like(weights_results[0][0][i]) for i in range(len(weights_results[0][0]))
            ]
            for weights, num_examples in weights_results:
                for i, layer in enumerate(weights):
                    aggregated_weights[i] += layer * num_examples
            aggregated_weights = [w / total_examples for w in aggregated_weights]
            parameters_aggregated = ndarrays_to_parameters(aggregated_weights)

        self.history["rounds"].append(server_round)
        if results:
            acc = results[0][1].metrics.get("fl_accuracy", 0)
            self.history["global_acc"].append(acc)
            print(f"[serverx] Round {server_round} Acc: {acc:.4f}")

        return parameters_aggregated, {}

    def configure_evaluate(self, *a, **k):
        return []

    def aggregate_evaluate(self, *a, **k):
        return None, {}

    def evaluate(self, *a, **k):
        return None


NUM_ROUNDS = 1

if __name__ == "__main__":
    strategy = ServerXStrategy(total_rounds=NUM_ROUNDS, use_he=USE_HE)
    fl.server.start_server(
        server_address="0.0.0.0:8081",
        config=fl.server.ServerConfig(num_rounds=NUM_ROUNDS),
        strategy=strategy,
    )
    print(f"[serverx] Eavesdrop data saved to {EAVESDROP_OUT_DIR}/")
