# This file was generated by team member Mingyang Xue(20617494)
from typing import Dict, List, Tuple

import numpy as np
from flwr.common import parameters_to_ndarrays

from ..config import FLConfig
from ..utils import train, test


def maybe_random_disconnect(
    cfg: FLConfig,
    cid: int,
    round_num: int,
    net_isolated,
    trainloader,
    testloader,
    disconnect_prob: float,
    missed_rounds: int,
):
    """Client-side random disconnection logic.

    Returns (handled, missed_rounds, fit_return_tuple_or_none).
    """
    import random

    if not cfg.use_random_disconnection or disconnect_prob <= 0.0:
        return False, missed_rounds, None

    if random.random() < disconnect_prob:
        missed_rounds += 1
        print(
            f"[Client {cid}] Round {round_num}: DISCONNECTED "
            f"(missed {missed_rounds} rounds)"
        )
        # Return empty NDArrays list (server ignores because num_examples == 0)
        return True, missed_rounds, (
            [],  # empty NDArrays list
            0,
            {
                "cid": cid,
                "disconnected": True,
                "missed_rounds": missed_rounds,
                "fl_accuracy": 0.0,
            },
        )

    if missed_rounds > 0:
        print(
            f"[Client {cid}] Round {round_num}: reconnected after "
            f"{missed_rounds} missed rounds"
        )
        missed_rounds = 0

    return False, missed_rounds, None


def build_weight_results_with_history(
    cfg: FLConfig,
    server_round: int,
    active_updates: List[Tuple[int, bytes, int, dict]],
    client_latest_updates: Dict[int, dict],
):
    """Server-side helper to add historical updates for missing clients."""
    weights_results: List[Tuple[int, List[np.ndarray], int, bool]] = []
    active_cids = set()

    for cid, params, num_examples, _metrics in active_updates:
        active_cids.add(cid)
        nds = parameters_to_ndarrays(params)
        client_latest_updates[cid] = {
            "parameters": params,
            "num_examples": num_examples,
            "round": server_round,
        }
        weights_results.append((cid, nds, num_examples, False))

    stale_count = 0
    if cfg.use_history_updates:
        all_possible_cids = set(range(1, cfg.num_clients + 1))
        missing_cids = all_possible_cids - active_cids
        for cid in missing_cids:
            hist = client_latest_updates.get(cid)
            if not hist:
                continue
            stale_rounds = server_round - hist["round"]
            if stale_rounds <= cfg.max_stale_rounds:
                nds = parameters_to_ndarrays(hist["parameters"])
                num_examples = int(hist["num_examples"])
                decay = max(0.5, 1.0 - 0.1 * stale_rounds)
                decayed_examples = int(num_examples * decay)
                weights_results.append((cid, nds, decayed_examples, True))
                stale_count += 1
                print(
                    f"   [SERVER] Using historical update from client {cid}, "
                    f"{stale_rounds} rounds old (decay factor {decay:.2f})"
                )

    return weights_results, stale_count

