# This file was generated by team member Jiale Qin(20616174)
from typing import Dict, List, Tuple

import numpy as np
from flwr.common import ndarrays_to_parameters, parameters_to_ndarrays

from ..config import FLConfig

from ..he_utils import (
    PaillierHE,
    generate_encryption_masks,
    deserialize_partial_encrypted_parameters,
    secure_aggregate_partial_encrypted,
    init_he_from_config,
    encrypt_and_return_params,
)


def init_server_he(cfg: FLConfig) -> PaillierHE | None:
    """Initialize Paillier HE on the server side if enabled."""
    if not cfg.use_he:
        return None
    print("[SERVER] Initializing Paillier HE for partial encryption...")
    return PaillierHE(key_size=1024)


def aggregate_round_he(
    cfg: FLConfig,
    server_round: int,
    active_updates: List[Tuple[int, bytes, int, dict]],
    he: PaillierHE,
    history: Dict[str, dict],
    previous_parameters,
):
    """HE-based secure aggregation for one round.

    `active_updates` is a list of (cid, flower_parameters, num_examples, metrics).
    """
    import pickle

    print(f"[SERVER] Round {server_round}: HE secure aggregation over {len(active_updates)} clients")

    if not active_updates:
        return previous_parameters

    # Decode first client's parameters to reconstruct shapes and masks
    first_params = active_updates[0][1]
    param_bytes_list = parameters_to_ndarrays(first_params)
    serialized_params_0 = [pickle.loads(p.tobytes()) for p in param_bytes_list]
    shapes = [s["shape"] for s in serialized_params_0]
    dummy = [np.zeros(shape, dtype=np.float64) for shape in shapes]
    masks = generate_encryption_masks(
        dummy,
        encrypt_ratio=cfg.he_encrypt_ratio,
        seed=cfg.he_mask_seed,
    )

    encrypted_params_list = []
    num_examples_list = []
    fl_accs = []

    for cid, params, num_examples, metrics in active_updates:
        param_bytes = parameters_to_ndarrays(params)
        serialized_params = [pickle.loads(p.tobytes()) for p in param_bytes]
        mixed = deserialize_partial_encrypted_parameters(serialized_params, masks)
        encrypted_params_list.append(mixed)
        num_examples_list.append(num_examples)
        fl_accs.append(metrics.get("fl_accuracy", 0.0))
        print(f"  [SERVER][HE] received client {cid} with {num_examples} examples")

    aggregated_encrypted = secure_aggregate_partial_encrypted(
        encrypted_params_list,
        num_examples_list,
        he.public_key,
        masks,
    )

    print("[SERVER] Decrypting aggregated parameters...")
    aggregated_weights = he.decrypt_parameters_partial(aggregated_encrypted, masks)
    aggregated_weights = [w.reshape(s) for w, s in zip(aggregated_weights, shapes)]

    total_examples = sum(num_examples_list)
    aggregated_weights = [layer / total_examples for layer in aggregated_weights]
    aggregated_params = ndarrays_to_parameters(aggregated_weights)

    return aggregated_params


def init_client_he(config: dict, cid: int):
    """Client-side HE initialization (wrapper around flower_privacy helper)."""
    return init_he_from_config(config, client_id=cid)


def encrypt_client_update(
    updated_params,
    he,
    use_he: bool,
    cid: int,
    num_examples: int,
    metrics: dict,
    config: dict,
):
    """Client-side encryption (or plain upload) wrapper."""
    return encrypt_and_return_params(
        updated_params,
        he,
        use_he,
        client_id=cid,
        num_examples=num_examples,
        metrics=metrics,
        config=config,
    )

