# This file was generated by team member Sirui LI(20617511)

from typing import Dict, List, Tuple

import numpy as np
from ..config import FLConfig
from ..utils import poison_dataset, train, test


def maybe_apply_poisoning(trainloader, cid: int, enable_poisoning: bool, is_poisoned_flag: bool):
    """Apply label-flip poisoning once on a chosen client (e.g., cid == 1)."""
    if not enable_poisoning or is_poisoned_flag:
        return is_poisoned_flag
    if cid != 1:
        return is_poisoned_flag
    print(f"[Client {cid}] Applying label-flip poisoning...")
    train_subset = trainloader.dataset
    poison_dataset(train_subset, source_label=0, target_label=3)
    poison_dataset(train_subset, source_label=1, target_label=9)
    poison_dataset(train_subset, source_label=2, target_label=8)
    # poison_dataset(train_subset, source_label=3, target_label=0)
    return True


def aggregate_with_mad_reputation(
    cfg: FLConfig,
    weights_results: List[Tuple[int, List[np.ndarray], int, bool]],
    client_trusts: Dict[int, float],
    client_trust_history: Dict[int, List[float]],
):
    """Aggregate using MAD + reputation defense (no HE, coordinate-wise)."""
    cids = [cid for cid, _, _, _ in weights_results]
    all_weights = [nds for _, nds, _, _ in weights_results]
    num_examples_array = np.array([w for _, _, w, _ in weights_results], dtype=np.float64)
    num_layers = len(all_weights[0])
    aggregated_weights: List[np.ndarray] = []

    # Initialize trusts if needed
    for cid in cids:
        if cid not in client_trusts:
            client_trusts[cid] = 1.0
        if cid not in client_trust_history:
            client_trust_history[cid] = []

    sigma = cfg.defense_sigma

    round_trust_sums = np.zeros(len(cids), dtype=np.float64)
    total_params = 0
    historical_trust_np = np.array([client_trusts[cid] for cid in cids], dtype=np.float64)

    for layer_idx in range(num_layers):
        layer_stack = np.stack([w[layer_idx] for w in all_weights], axis=0)

        layer_median = np.median(layer_stack, axis=0)
        abs_dev = np.abs(layer_stack - layer_median)
        mad = np.median(abs_dev, axis=0)
        mad_safe = np.maximum(mad, 1e-5)
        scores = 0.6745 * abs_dev / mad_safe

        coord_trust = np.exp(-(scores ** 2) / (2 * sigma ** 2))

        # Accumulate per-client coordinate trust for EMA reputation
        num_layer_params = int(np.prod(coord_trust.shape[1:]))
        round_trust_sums += coord_trust.reshape(len(cids), -1).sum(axis=1)
        total_params += num_layer_params

        # Combine coordinate trust with historical client trust
        broadcast_shape = [-1] + [1] * (coord_trust.ndim - 1)
        combined_trust = coord_trust * historical_trust_np.reshape(broadcast_shape)
        sum_combined_trust = np.sum(combined_trust, axis=0)
        final_layer_update = np.sum(layer_stack * combined_trust, axis=0) / np.maximum(sum_combined_trust, 1e-8)
        aggregated_weights.append(final_layer_update)

    # Update per-client trust via EMA
    alpha = cfg.trust_ema_alpha
    round_scores = round_trust_sums / max(total_params, 1e-8)
    print("--- Reputation scores this round ---")
    for idx, cid in enumerate(cids):
        new_trust = alpha * client_trusts[cid] + (1 - alpha) * round_scores[idx]
        client_trusts[cid] = float(new_trust)
        client_trust_history[cid].append(float(new_trust))
        print(f"  Client {cid}: round_score={round_scores[idx]:.4f}, trust={new_trust:.4f}")

    return aggregated_weights

